cc_library(
    name = "built_with_bazel_2",
    srcs = ["builtWithBazel2.c"],
    hdrs = [
        "builtWithBazel2.h",
        "detail/builtWithBazel2.h",
    ],
    visibility = ["//visibility:public"]
)