load(":cmake_text_tests.bzl", "cmake_script_test_suite")
load(":convert_shell_script_test.bzl", "shell_script_conversion_suite")
load(":utils_test.bzl", "utils_test_suite")

cmake_script_test_suite()

shell_script_conversion_suite()

utils_test_suite()
