---
validate_config: 1

matrix:
  platform:
    - ubuntu2204
    - ubuntu2404
    - rbe_ubuntu2204
    - macos
    - macos_arm64
    - windows

  bazel_version:
    # 7.x: 7.7.1
    7.x: 7.4.1
    # 8.x: 8.5.1
    # 9.x: 9.0.0

  bzlmod:
    bzlmod: ["--enable_bzlmod", "--noenable_workspace"]
    workspaces: ["--noenable_bzlmod", "--enable_workspace"]
    mixed: ["--enable_bzlmod", "--enable_workspace"]

  spawn_strategy:
    default: "--config=spawn-default"
    standalone: "--config=spawn-standalone"

  exclude:
    # bazel 9 no longer supports workspaces
    - bazel_version: 9.x
      bzlmod: workspaces

    # bazel 9 no longer supports workspaces
    - bazel_version: 9.x
      bzlmod: mixed

    # Only support workspaces with bazel 7
    - bazel_version: 7.x
      bzlmod: bzlmod

    # Only support workspaces with bazel 7
    - bazel_version: 7.x
      bzlmod: mixed

    # Windows currently doesn't work in bzlmod mode (XXX maybe?)
    - platform: windows
      bzlmod: bzlmod

    # Windows currently doesn't work in bzlmod mode (XXX maybe?)
    - platform: windows
      bzlmod: mixed

    # Windows doesn't actually have a sandbox anyway, and there aren't a lot of
    # windows runners, so don't run the standalones
    - platform: windows
      spawn_strategy: standalone


tasks:
  main:
    name: "Main/{bazel_version}/{bzlmod}"
    platform: ${{ platform }}
    bazel: ${{ bazel_version }}

    build_targets: &main_targets
      - "//..."
    build_flags: &main_flags
      - "--@aspect_rules_lint//lint:fail_on_violation"
      - ${{ bzlmod }}
    test_targets: *main_targets
    test_flags: *main_flags

  examples:
    name: "Examples/{bazel_version}/{bzlmod}/{spawn_strategy}"
    platform: ${{ platform }}
    bazel: ${{ bazel_version }}
    working_directory: examples
    build_targets: &examples_targets
      - "//..."
    build_flags: &examples_flags
      - "-c"
      - "dbg"
      - ${{ spawn_strategy }}
      - ${{ bzlmod }}
    test_targets: *examples_targets
    test_flags: *examples_flags

  flags:
    name: "Flags/{bazel_version}/{bzlmod}"
    platform: ${{ platform }}
    bazel: ${{ bazel_version }}
    working_directory: test/standard_cxx_flags_test
    test_targets:
      - "//..."
    test_flags:
      - ${{ bzlmod }}

  detect_root:
    name: "DetectRoot/{bazel_version}/{bzlmod}"
    platform: ${{ platform }}
    bazel: ${{ bazel_version }}
    working_directory: test/detect_root_test
    test_targets:
      - "//..."
    test_flags:
      - ${{ bzlmod }}

  docs:
    name: Docs
    platform: ubuntu2404
    working_directory: docs
    build_targets:
      - //...

buildifier:
  version: "8.2.1"
  # keep this argument in sync with .pre-commit-config.yaml
  warnings: "all"
