validate_config: 1

matrix:
  platform:
    - ubuntu2204
    - ubuntu2404
    - rbe_ubuntu2204
    - macos
    - macos_arm64
    - windows

  bazel_version:
    7.x: 7.7.1
    # 8.x: 8.6.0
    # 9.x: 9.0.1

  bzlmod:
    bzlmod: [--enable_bzlmod, --noenable_workspace]
    workspaces: [--noenable_bzlmod, --enable_workspace]
    mixed: [--enable_bzlmod, --enable_workspace]

  spawn_strategy:
    default: --config=spawn-default
    standalone: --config=spawn-standalone

  primary:
    Main: ''
    Examples: examples

  exclude:
    # bazel 9 no longer supports workspaces
    - bazel_version: 9.x
      bzlmod: workspaces

    # Windows doesn't actually have a sandbox anyway, and there aren't a lot of
    # windows runners, so don't run the standalones
    - platform: windows
      spawn_strategy: standalone

    # Only examples should be run in standalone mode (to reduce the number of jobs)
    - primary: Main
      spawn_strategy: standalone

    # The RBE config does not work with workspaces disabled, since it must be
    # invoked from WORKSPACE.bzlmod
    - platform: rbe_ubuntu2204
      bzlmod: bzlmod

# Note: we're not using the default_flags idiom because the matrix expander
# currently can't handle expanding dict keys
.default_task: &default_task
  platform: ${{ platform }}
  bazel: ${{ bazel_version }}
  build_targets:
    - //...
  test_targets:
    - //...

tasks:
  primary:
    <<: *default_task
    name: '{primary}/{bazel_version}/{bzlmod}/{spawn_strategy}'
    working_directory: ${{ primary }}

    build_flags: &primary_flags
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

    test_flags: *primary_flags

  docs:
    name: Docs
    platform: ubuntu2404
    working_directory: docs
    build_targets:
      - //...
    build_flags:
      - --config=ci

buildifier:
  version: 8.2.1
  # keep this argument in sync with .pre-commit-config.yaml
  warnings: all
