validate_config: 1

matrix:
  platform:
    - ubuntu2404
    - macos
    - macos_arm64
    - windows

  bazel_version:
    7.x: 7.7.1
    8.x: 8.6.0
    # 9.x: 9.0.1

  # hack to work around it until the fix lands:
  # https://github.com/bazelbuild/continuous-integration/pull/2526
  bazel_rc_config:
    7.x: --config=bazel-7.x
    8.x: --config=bazel-8.x

  bzlmod:
    bzlmod: [--enable_bzlmod, --noenable_workspace]

  spawn_strategy:
    default: --config=spawn-default

  primary:
    Main: ''

  exclude:
    # bazel 9 no longer supports workspaces
    - bazel_version: 9.x
      bzlmod: workspaces

    # bazel 7 has an unfortunate habit of crashing on bzlmod lock files, so
    # only support bazel 7 in workspace mode
    - bazel_version: 7.x
      bzlmod: bzlmod

    - bazel_version: 7.x
      bzlmod: mixed

    - bazel_version: 7.x
      bazel_rc_config: 8.x

    - bazel_version: 8.x
      bazel_rc_config: 7.x

    # Windows doesn't actually have a sandbox anyway, and there aren't a lot of
    # windows runners, so don't run the standalones
    - platform: windows
      spawn_strategy: standalone

    # Only examples should be run in standalone mode (to reduce the number of jobs)
    - primary: Main
      spawn_strategy: standalone

    # The RBE config does not work with workspaces disabled, since it must be
    # invoked from WORKSPACE.bzlmod
    - platform: rbe_ubuntu2204
      bzlmod: bzlmod

# Note: we're not using the default_flags idiom because the matrix expander
# currently can't handle expanding dict keys
.default_task: &default_task
  platform: ${{ platform }}
  bazel: ${{ bazel_version }}
  build_targets:
    - //test/facade_binary:all
    - //test/facade_chain:all
    - //test/facade_foreign_shared_library:all
    - //test/facade_library:all
    - //test/facade_multi_library:all
    - //test/facade_shared_library_conflicts:all
    - //test/facade_shared_library:all
    - //test/facade_static_library:all
    - //test/cc_toolchain_probe:probe_test
  test_targets:
    - //test/facade_binary:all
    - //test/facade_chain:all
    - //test/facade_foreign_shared_library:all
    - //test/facade_library:all
    - //test/facade_multi_library:all
    - //test/facade_shared_library_conflicts:all
    - //test/facade_shared_library:all
    - //test/facade_static_library:all
    - //test/cc_toolchain_probe:probe_test

tasks:
  primary:
    <<: *default_task
    name: '{primary}/{bazel_version}/{bzlmod}/{spawn_strategy}'
    working_directory: ${{ primary }}

    build_flags: &primary_flags
      - --config=ci
      - ${{ bazel_rc_config }}
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

    test_flags: *primary_flags

  native_static_probe:
    name: 'NativeStaticProbe/{bazel_version}/{bzlmod}/{spawn_strategy}'
    platform: ubuntu2404
    bazel: ${{ bazel_version }}
    build_targets:
      - //test/native_static_library:all
    test_targets:
      - //test/native_static_library:all
    build_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}
      - --experimental_cc_static_library
    test_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}
      - --experimental_cc_static_library

  flags_probe:
    name: 'FlagsProbe/{bazel_version}/{bzlmod}/{spawn_strategy}'
    platform: ubuntu2404
    bazel: ${{ bazel_version }}
    working_directory: examples
    test_targets:
      - //integration_tests/standard_cxx_flags_test:flags_test
    test_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

  detect_root_probe:
    name: 'DetectRootProbe/{bazel_version}/{bzlmod}/{spawn_strategy}'
    platform: ubuntu2404
    bazel: ${{ bazel_version }}
    working_directory: examples
    test_targets:
      - //integration_tests/detect_root_test:tests
    test_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

  docs_probe:
    name: 'DocsProbe/{bazel_version}/{bzlmod}/{spawn_strategy}'
    platform: ubuntu2404
    bazel: ${{ bazel_version }}
    working_directory: docs
    test_targets:
      - //:docs_build_test
    test_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

  env_probe:
    name: 'EnvProbe/{bazel_version}/{bzlmod}/{spawn_strategy}'
    platform: ubuntu2404
    bazel: ${{ bazel_version }}
    test_targets:
      - //test/env_test:ninja_tiny_env_test_shellvars_check
    test_flags:
      - --config=ci
      - ${{ bzlmod }}
      - ${{ spawn_strategy }}

  docs:
    name: Docs
    platform: ubuntu2404
    working_directory: docs
    build_targets:
      - //...
    build_flags:
      - --config=ci
buildifier:
  version: 8.2.1
  # keep this argument in sync with .pre-commit-config.yaml
  warnings: all
