#!/bin/bash --norc

if [ -z "${EXT_BUILD_ROOT}" ]; then
    PREFIX=""
else
    PREFIX="${EXT_BUILD_ROOT}/"
fi
PATH="${PREFIX}external/org_linaro_components_toolchain_gcc_5_3_1/libexec/gcc/arm-linux-gnueabihf/4.9.3:$PATH" \
    exec \
    ${PREFIX}external/org_linaro_components_toolchain_gcc_5_3_1/bin/arm-linux-gnueabihf-gcc \
    "$@"
