#!/bin/bash --norc

if [ -z "${EXT_BUILD_ROOT}" ]; then
    PREFIX=""
else
    PREFIX="${EXT_BUILD_ROOT}/"
fi
exec -a arm-linux-gnueabihf-as \
    ${PREFIX}/external/org_linaro_components_toolchain_gcc_5_3_1/bin/arm-linux-gnueabihf-as \
    "$@"
