""" A U T O G E N E R A T E D  -- D O   N O T   M O D I F Y
@generated

This file is generated by prebuilt_toolchains.py

"""

CMAKE_SRCS = {
    "3.19.8": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8.tar.gz",
        ],
        "cmake-3.19.8",
        "09b4fa4837aae55c75fb170f6a6e2b44818deba48335d1969deddfbb34e30369",
    ],
    "3.19.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8.tar.gz",
        ],
        "cmake-3.19.8",
        "09b4fa4837aae55c75fb170f6a6e2b44818deba48335d1969deddfbb34e30369",
    ],
    "3.20.6": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6.tar.gz",
        ],
        "cmake-3.20.6",
        "a0bd485e1a38dd13c0baec89d5f4adbf61c7fd32fddb38eabc69a75bc0b65d72",
    ],
    "3.20.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6.tar.gz",
        ],
        "cmake-3.20.6",
        "a0bd485e1a38dd13c0baec89d5f4adbf61c7fd32fddb38eabc69a75bc0b65d72",
    ],
    "3.21.7": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7.tar.gz",
        ],
        "cmake-3.21.7",
        "3523c4a5afc61ac3d7c92835301cdf092129c9b672a6ee17e68c92e928c1375a",
    ],
    "3.21.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7.tar.gz",
        ],
        "cmake-3.21.7",
        "3523c4a5afc61ac3d7c92835301cdf092129c9b672a6ee17e68c92e928c1375a",
    ],
    "3.22.6": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6.tar.gz",
        ],
        "cmake-3.22.6",
        "73933163670ea4ea95c231549007b0c7243282293506a2cf4443714826ad5ec3",
    ],
    "3.22.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6.tar.gz",
        ],
        "cmake-3.22.6",
        "73933163670ea4ea95c231549007b0c7243282293506a2cf4443714826ad5ec3",
    ],
    "3.23.5": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5.tar.gz",
        ],
        "cmake-3.23.5",
        "f2944cde7a140b992ba5ccea2009a987a92413762250de22ebbace2319a0f47d",
    ],
    "3.23.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5.tar.gz",
        ],
        "cmake-3.23.5",
        "f2944cde7a140b992ba5ccea2009a987a92413762250de22ebbace2319a0f47d",
    ],
    "3.24.4": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4.tar.gz",
        ],
        "cmake-3.24.4",
        "32c9e499510eff7070d3f0adfbabe0afea2058608c5fa93e231beb49fbfa2296",
    ],
    "3.24.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4.tar.gz",
        ],
        "cmake-3.24.4",
        "32c9e499510eff7070d3f0adfbabe0afea2058608c5fa93e231beb49fbfa2296",
    ],
    "3.25.3": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3.tar.gz",
        ],
        "cmake-3.25.3",
        "cc995701d590ca6debc4245e9989939099ca52827dd46b5d3592f093afe1901c",
    ],
    "3.25.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3.tar.gz",
        ],
        "cmake-3.25.3",
        "cc995701d590ca6debc4245e9989939099ca52827dd46b5d3592f093afe1901c",
    ],
    "3.26.6": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6.tar.gz",
        ],
        "cmake-3.26.6",
        "070b9a2422e666d2c1437e2dab239a236e8a63622d0a8d0ffe9e389613d2b76a",
    ],
    "3.26.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6.tar.gz",
        ],
        "cmake-3.26.6",
        "070b9a2422e666d2c1437e2dab239a236e8a63622d0a8d0ffe9e389613d2b76a",
    ],
    "3.27.9": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9.tar.gz",
        ],
        "cmake-3.27.9",
        "609a9b98572a6a5ea477f912cffb973109ed4d0a6a6b3f9e2353d2cdc048708e",
    ],
    "3.27.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9.tar.gz",
        ],
        "cmake-3.27.9",
        "609a9b98572a6a5ea477f912cffb973109ed4d0a6a6b3f9e2353d2cdc048708e",
    ],
    "3.28.6": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6.tar.gz",
        ],
        "cmake-3.28.6",
        "c39c733900affc4eb0e9688b4d1a45435a732105d9bf9cc1e75dd2b9b81a36bb",
    ],
    "3.28.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6.tar.gz",
        ],
        "cmake-3.28.6",
        "c39c733900affc4eb0e9688b4d1a45435a732105d9bf9cc1e75dd2b9b81a36bb",
    ],
    "3.29.9": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9.tar.gz",
        ],
        "cmake-3.29.9",
        "467701a2816573f8767741379cb138f0fff4acf364e15ef0b1b88734ac7fab5b",
    ],
    "3.29.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9.tar.gz",
        ],
        "cmake-3.29.9",
        "467701a2816573f8767741379cb138f0fff4acf364e15ef0b1b88734ac7fab5b",
    ],
    "3.30.9": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9.tar.gz",
        ],
        "cmake-3.30.9",
        "65f765bb87c8019316cabe67cbe5e8f45ede334eeb5afd161ca6874d17994e0d",
    ],
    "3.30.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9.tar.gz",
        ],
        "cmake-3.30.9",
        "65f765bb87c8019316cabe67cbe5e8f45ede334eeb5afd161ca6874d17994e0d",
    ],
    "3.31.12": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12.tar.gz",
        ],
        "cmake-3.31.12",
        "5f3fd5a54dfa65602bdbed64f981a72673cc19f2d304cc2955cf0dfa0cfd8272",
    ],
    "3.31.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12.tar.gz",
        ],
        "cmake-3.31.12",
        "5f3fd5a54dfa65602bdbed64f981a72673cc19f2d304cc2955cf0dfa0cfd8272",
    ],
    "4.0.7": [
        [
            "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7.tar.gz",
        ],
        "cmake-4.0.7",
        "356921178d017782d9701aedd097b51c1e92e186e941011ea30039a2509d9417",
    ],
    "4.0.x": [
        [
            "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7.tar.gz",
        ],
        "cmake-4.0.7",
        "356921178d017782d9701aedd097b51c1e92e186e941011ea30039a2509d9417",
    ],
}
