""" A U T O G E N E R A T E D  -- D O   N O T   M O D I F Y
@generated

This file is generated by prebuilt_toolchains.py
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@rules_foreign_cc//toolchains:prebuilt_toolchains_repository.bzl", "prebuilt_toolchains_repository")

_CMAKE_BUILD_FILE = """\
load("@rules_foreign_cc//toolchains/native_tools:native_tools_toolchain.bzl", "native_tool_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cmake_bin",
    srcs = ["bin/{bin}"],
)

filegroup(
    name = "cmake_data",
    srcs = glob(
        [
            "**",
        ],
        exclude = [
            "WORKSPACE",
            "WORKSPACE.bazel",
            "BUILD",
            "BUILD.bazel",
            "**/* *",
        ],
    ),
)

native_tool_toolchain(
    name = "cmake_tool",
    path = "bin/{bin}",
    target = ":cmake_data",
    env = {env},
    tools = [":cmake_bin"],
)
"""

_NINJA_BUILD_FILE = """\
load("@rules_foreign_cc//toolchains/native_tools:native_tools_toolchain.bzl", "native_tool_toolchain")
load("@rules_foreign_cc//foreign_cc/private:select_executable.bzl", "select_executable")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "ninja_bin",
    srcs = ["{bin}"],
)

select_executable(
    name = "ninja_wrapper_bin",
    src = "{wrapper}",
)

filegroup(
    name = "ninja_data",
    srcs = [
        ":ninja_bin",
        "{wrapper}",
    ]
)

native_tool_toolchain(
    name = "ninja_tool",
    env = {env},
    path = "$(execpath :ninja_wrapper_bin)",
    target = ":ninja_data",
    tools = [
        ":ninja_bin",
        ":ninja_wrapper_bin",
    ]
)
"""

# buildifier: disable=unnamed-macro
def prebuilt_toolchains(cmake_version, ninja_version, register_toolchains):
    """Register toolchains for pre-built cmake and ninja binaries

    Args:
        cmake_version (string): The target cmake version
        ninja_version (string): The target ninja-build version
        register_toolchains (boolean): Whether to call native.register_toolchains or not
    """
    _cmake_toolchains(cmake_version, register_toolchains)
    _ninja_toolchains(ninja_version, register_toolchains)

def _cmake_toolchains(version, register_toolchains):
    if "4.0.x" == version or "4.0.7" == version:
        maybe(
            http_archive,
            name = "cmake-4.0.7-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-aarch64.tar.gz",
            ],
            sha256 = "ad77fb21981b774f5d33b5ec0987071d93fee1d080599f7f61e59545f4cb0b50",
            strip_prefix = "cmake-4.0.7-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-4.0.7-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-x86_64.tar.gz",
            ],
            sha256 = "dba36a8e7898e02c3a66dbe169dc776ffc81c2ee6d5bcab3c526d3f3976b4e91",
            strip_prefix = "cmake-4.0.7-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-4.0.7-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-macos-universal.tar.gz",
            ],
            sha256 = "dba00f8ad22a832dad0f6754e62384780684a4c9d127de472fb0e92df719f1c4",
            strip_prefix = "cmake-4.0.7-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-4.0.7-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-i386.zip",
            ],
            sha256 = "d1252c83ccf19511ae5ed54497b8488fd9b96e0f2b1f7fbb97bfdb55edb9067f",
            strip_prefix = "cmake-4.0.7-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-4.0.7-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-x86_64.zip",
            ],
            sha256 = "3c0bfe3ef9956b39a741afe1385499969bcd100dba7b5076d648bd2fbc56131c",
            strip_prefix = "cmake-4.0.7-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_4.0.7_toolchains",
            repos = {
                "cmake-4.0.7-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-4.0.7-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-4.0.7-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-4.0.7-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-4.0.7-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_4.0.7_toolchains//:cmake-4.0.7-linux-aarch64_toolchain",
                "@cmake_4.0.7_toolchains//:cmake-4.0.7-linux-x86_64_toolchain",
                "@cmake_4.0.7_toolchains//:cmake-4.0.7-macos-universal_toolchain",
                "@cmake_4.0.7_toolchains//:cmake-4.0.7-windows-i386_toolchain",
                "@cmake_4.0.7_toolchains//:cmake-4.0.7-windows-x86_64_toolchain",
            )

        return

    if "3.31.x" == version or "3.31.12" == version:
        maybe(
            http_archive,
            name = "cmake-3.31.12-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-aarch64.tar.gz",
            ],
            sha256 = "83f8fd91d2038a56556e1400390fcfe42f79602940c494f6c6f1cdae7f9e7f40",
            strip_prefix = "cmake-3.31.12-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.31.12-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-x86_64.tar.gz",
            ],
            sha256 = "0dc2e9a6860f06bf10bd8fadc03e35d9eeb4df46e33763a7e480e987758f385c",
            strip_prefix = "cmake-3.31.12-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.31.12-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-macos-universal.tar.gz",
            ],
            sha256 = "799af7fd545db9bf1b9cfe72f8095880e727a2d4e0df0e3dffc3bc7b95c2d3b0",
            strip_prefix = "cmake-3.31.12-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.31.12-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-i386.zip",
            ],
            sha256 = "722c3b553e18e8bb1a038474b4d7c52159c00a37b5e04091434507ccd4ce162c",
            strip_prefix = "cmake-3.31.12-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.31.12-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-x86_64.zip",
            ],
            sha256 = "0c4baa40f28b3f8225eb3fdf6946c987b4fe901403b4eaf2fbbd9378100aaa0c",
            strip_prefix = "cmake-3.31.12-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.31.12_toolchains",
            repos = {
                "cmake-3.31.12-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.31.12-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.31.12-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.31.12-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.31.12-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.31.12_toolchains//:cmake-3.31.12-linux-aarch64_toolchain",
                "@cmake_3.31.12_toolchains//:cmake-3.31.12-linux-x86_64_toolchain",
                "@cmake_3.31.12_toolchains//:cmake-3.31.12-macos-universal_toolchain",
                "@cmake_3.31.12_toolchains//:cmake-3.31.12-windows-i386_toolchain",
                "@cmake_3.31.12_toolchains//:cmake-3.31.12-windows-x86_64_toolchain",
            )

        return

    if "3.30.x" == version or "3.30.9" == version:
        maybe(
            http_archive,
            name = "cmake-3.30.9-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-aarch64.tar.gz",
            ],
            sha256 = "9ae2b709ed3aaef504dd25fb6abe7dd4df68cd46824e45d7ee89ae57951d215a",
            strip_prefix = "cmake-3.30.9-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.30.9-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-x86_64.tar.gz",
            ],
            sha256 = "9114e33358a9efc93d6ea658805280fc3201b882b944a4d946edd9472fd1eec7",
            strip_prefix = "cmake-3.30.9-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.30.9-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-macos-universal.tar.gz",
            ],
            sha256 = "572bf27e2e98d7513e0835525a2b9dc0f3947f6ad7494615e22b60369e87db11",
            strip_prefix = "cmake-3.30.9-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.30.9-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-i386.zip",
            ],
            sha256 = "0ec7d45b8705f019015dca50603600bb68407201f94205f3cba6d1004da5c086",
            strip_prefix = "cmake-3.30.9-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.30.9-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-x86_64.zip",
            ],
            sha256 = "b60b316b4827852b3f49f3a6e35e1a9c2301f8c2dca81d135ba0731d4fd9338b",
            strip_prefix = "cmake-3.30.9-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.30.9_toolchains",
            repos = {
                "cmake-3.30.9-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.30.9-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.30.9-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.30.9-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.30.9-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.30.9_toolchains//:cmake-3.30.9-linux-aarch64_toolchain",
                "@cmake_3.30.9_toolchains//:cmake-3.30.9-linux-x86_64_toolchain",
                "@cmake_3.30.9_toolchains//:cmake-3.30.9-macos-universal_toolchain",
                "@cmake_3.30.9_toolchains//:cmake-3.30.9-windows-i386_toolchain",
                "@cmake_3.30.9_toolchains//:cmake-3.30.9-windows-x86_64_toolchain",
            )

        return

    if "3.29.x" == version or "3.29.9" == version:
        maybe(
            http_archive,
            name = "cmake-3.29.9-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-aarch64.tar.gz",
            ],
            sha256 = "3fc32b2c0701b16d42db5e5062bdb6bf5b6ef831278535ee5946793fa4460954",
            strip_prefix = "cmake-3.29.9-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.29.9-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-x86_64.tar.gz",
            ],
            sha256 = "dd433a0d9babf08cbd79eac319c06b8287929ad88ff8c1b83cbc6cfd5ea90acc",
            strip_prefix = "cmake-3.29.9-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.29.9-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-macos-universal.tar.gz",
            ],
            sha256 = "4502ccc9f9eb9e7bf495666b637a9e63a695537b0d0850c1ca0ebcc61c5149e5",
            strip_prefix = "cmake-3.29.9-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.29.9-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-i386.zip",
            ],
            sha256 = "70556ace59d1651fcc40a1712d9a6d900791cc21235ece7158ca7244410c1005",
            strip_prefix = "cmake-3.29.9-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.29.9-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-x86_64.zip",
            ],
            sha256 = "7858d849d4061b0684366a81701a9b2bad2d3c332a40cc67cf11eef40c08fddb",
            strip_prefix = "cmake-3.29.9-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.29.9_toolchains",
            repos = {
                "cmake-3.29.9-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.29.9-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.29.9-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.29.9-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.29.9-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.29.9_toolchains//:cmake-3.29.9-linux-aarch64_toolchain",
                "@cmake_3.29.9_toolchains//:cmake-3.29.9-linux-x86_64_toolchain",
                "@cmake_3.29.9_toolchains//:cmake-3.29.9-macos-universal_toolchain",
                "@cmake_3.29.9_toolchains//:cmake-3.29.9-windows-i386_toolchain",
                "@cmake_3.29.9_toolchains//:cmake-3.29.9-windows-x86_64_toolchain",
            )

        return

    if "3.28.x" == version or "3.28.6" == version:
        maybe(
            http_archive,
            name = "cmake-3.28.6-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-aarch64.tar.gz",
            ],
            sha256 = "7909cc2128ce9442c63ce674a0bfb0e4f4ce04cef667d887e15ad5670d594ba7",
            strip_prefix = "cmake-3.28.6-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.28.6-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-x86_64.tar.gz",
            ],
            sha256 = "931e3c0d546ee03ca72bb147ccd9b49e3b6252f765f66bf21b9d165519940458",
            strip_prefix = "cmake-3.28.6-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.28.6-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-macos-universal.tar.gz",
            ],
            sha256 = "e992f382a98839aefc9292142699af5d43952e3087509d7671aef0dbeb33e852",
            strip_prefix = "cmake-3.28.6-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.28.6-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-i386.zip",
            ],
            sha256 = "29503bc5525592c95a51a0f58eea9a9e38650dbbe7bbeb1caab7fc8f4048d7c5",
            strip_prefix = "cmake-3.28.6-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.28.6-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-x86_64.zip",
            ],
            sha256 = "a8f2e684ead94a64fd3517a38857a5b3f7f8d68d15c49ca1143d18797eaf9cac",
            strip_prefix = "cmake-3.28.6-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.28.6_toolchains",
            repos = {
                "cmake-3.28.6-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.28.6-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.28.6-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.28.6-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.28.6-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.28.6_toolchains//:cmake-3.28.6-linux-aarch64_toolchain",
                "@cmake_3.28.6_toolchains//:cmake-3.28.6-linux-x86_64_toolchain",
                "@cmake_3.28.6_toolchains//:cmake-3.28.6-macos-universal_toolchain",
                "@cmake_3.28.6_toolchains//:cmake-3.28.6-windows-i386_toolchain",
                "@cmake_3.28.6_toolchains//:cmake-3.28.6-windows-x86_64_toolchain",
            )

        return

    if "3.27.x" == version or "3.27.9" == version:
        maybe(
            http_archive,
            name = "cmake-3.27.9-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-aarch64.tar.gz",
            ],
            sha256 = "11bf3d30697df465cdf43664a9473a586f010c528376a966fd310a3a22082461",
            strip_prefix = "cmake-3.27.9-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.27.9-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.tar.gz",
            ],
            sha256 = "72b01478eeb312bf1a0136208957784fe55a7b587f8d9f9142a7fc9b0b9e9a28",
            strip_prefix = "cmake-3.27.9-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.27.9-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-macos-universal.tar.gz",
            ],
            sha256 = "ae1fdfd3f74864d0432f2e4a93ff6488125cd8f2869a40a1c2d5166feb6c607c",
            strip_prefix = "cmake-3.27.9-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.27.9-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-i386.zip",
            ],
            sha256 = "7296b5a46eb53bfd0e0ff1d818067745cb831ab8d3cef9d266bfc842a435d515",
            strip_prefix = "cmake-3.27.9-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.27.9-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-x86_64.zip",
            ],
            sha256 = "c14e8b5d1c7be0baf0e7936ce8b5a39c5ee3450b14d7e3b32435083eddd9aff7",
            strip_prefix = "cmake-3.27.9-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.27.9_toolchains",
            repos = {
                "cmake-3.27.9-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.27.9-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.27.9-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.27.9-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.27.9-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.27.9_toolchains//:cmake-3.27.9-linux-aarch64_toolchain",
                "@cmake_3.27.9_toolchains//:cmake-3.27.9-linux-x86_64_toolchain",
                "@cmake_3.27.9_toolchains//:cmake-3.27.9-macos-universal_toolchain",
                "@cmake_3.27.9_toolchains//:cmake-3.27.9-windows-i386_toolchain",
                "@cmake_3.27.9_toolchains//:cmake-3.27.9-windows-x86_64_toolchain",
            )

        return

    if "3.26.x" == version or "3.26.6" == version:
        maybe(
            http_archive,
            name = "cmake-3.26.6-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-aarch64.tar.gz",
            ],
            sha256 = "7b91a212b9e8ca38c1482ae40ff2d3e33e9d1c7b337b39f74bd4f34fd070bb1d",
            strip_prefix = "cmake-3.26.6-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.26.6-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-x86_64.tar.gz",
            ],
            sha256 = "2dd48ccd3e3d872ee4cc916f3f4e24812612421007e895f82bf9fc7e49831d62",
            strip_prefix = "cmake-3.26.6-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.26.6-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-macos-universal.tar.gz",
            ],
            sha256 = "2d7a4e5f48ad23ef962b5b7c602c4b0163dd44e51b6d4c33b336a1d663ab1445",
            strip_prefix = "cmake-3.26.6-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.26.6-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-i386.zip",
            ],
            sha256 = "dc3f535d880d1ffa7cfa86a0eefdc1fc9bf8b9ede59d1deb7a2bb41f0a58d2d4",
            strip_prefix = "cmake-3.26.6-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.26.6-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-x86_64.zip",
            ],
            sha256 = "07b1c4cae3182ca1782a4d9775b5e5d164b475eb010e1dd98ce0c206c38fa73d",
            strip_prefix = "cmake-3.26.6-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.26.6_toolchains",
            repos = {
                "cmake-3.26.6-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.26.6-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.26.6-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.26.6-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.26.6-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.26.6_toolchains//:cmake-3.26.6-linux-aarch64_toolchain",
                "@cmake_3.26.6_toolchains//:cmake-3.26.6-linux-x86_64_toolchain",
                "@cmake_3.26.6_toolchains//:cmake-3.26.6-macos-universal_toolchain",
                "@cmake_3.26.6_toolchains//:cmake-3.26.6-windows-i386_toolchain",
                "@cmake_3.26.6_toolchains//:cmake-3.26.6-windows-x86_64_toolchain",
            )

        return

    if "3.25.x" == version or "3.25.3" == version:
        maybe(
            http_archive,
            name = "cmake-3.25.3-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-aarch64.tar.gz",
            ],
            sha256 = "cd6e853639f858569e22e6298f009eb24b4702c51c0d5bc1cb36c688f7ce246d",
            strip_prefix = "cmake-3.25.3-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.25.3-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz",
            ],
            sha256 = "d4d2ba83301b215857d3b6590cd4434a414fa151c5807693abe587bd6c03581e",
            strip_prefix = "cmake-3.25.3-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.25.3-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-macos-universal.tar.gz",
            ],
            sha256 = "771548ed2abae17f3fd28dcfa572ba3fe9f970652a72c36c2e1aafdee93a234e",
            strip_prefix = "cmake-3.25.3-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.25.3-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-i386.zip",
            ],
            sha256 = "2e66cf7cbd35f392f6b9406910c68f4adfca1de9ab7a2fc4cec658c5c5cd9190",
            strip_prefix = "cmake-3.25.3-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.25.3-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-x86_64.zip",
            ],
            sha256 = "d129425d569140b729210f3383c246dec19c4183f7d0afae1837044942da3b4b",
            strip_prefix = "cmake-3.25.3-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.25.3_toolchains",
            repos = {
                "cmake-3.25.3-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.25.3-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.25.3-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.25.3-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.25.3-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.25.3_toolchains//:cmake-3.25.3-linux-aarch64_toolchain",
                "@cmake_3.25.3_toolchains//:cmake-3.25.3-linux-x86_64_toolchain",
                "@cmake_3.25.3_toolchains//:cmake-3.25.3-macos-universal_toolchain",
                "@cmake_3.25.3_toolchains//:cmake-3.25.3-windows-i386_toolchain",
                "@cmake_3.25.3_toolchains//:cmake-3.25.3-windows-x86_64_toolchain",
            )

        return

    if "3.24.x" == version or "3.24.4" == version:
        maybe(
            http_archive,
            name = "cmake-3.24.4-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-aarch64.tar.gz",
            ],
            sha256 = "86f823f2636bf715af89da10e04daa476755a799d451baee66247846e95d7bee",
            strip_prefix = "cmake-3.24.4-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.24.4-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-x86_64.tar.gz",
            ],
            sha256 = "cac77d28fb8668c179ac02c283b058aeb846fe2133a57d40b503711281ed9f19",
            strip_prefix = "cmake-3.24.4-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.24.4-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-macos-universal.tar.gz",
            ],
            sha256 = "16f68724ccd6c2e63e803d3d1dbc2961e5c84d3e123a7bf91825515d750eeac6",
            strip_prefix = "cmake-3.24.4-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.24.4-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-i386.zip",
            ],
            sha256 = "2839c1286e5a5f08316fc608af4911f7262cd50a166146bf561f2eec49ef2cd6",
            strip_prefix = "cmake-3.24.4-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.24.4-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-x86_64.zip",
            ],
            sha256 = "c135c7ab78143c46e6686b1e9652bc1dd07e0cf71fd4decee777cdca77019c39",
            strip_prefix = "cmake-3.24.4-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.24.4_toolchains",
            repos = {
                "cmake-3.24.4-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.24.4-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.24.4-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.24.4-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.24.4-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.24.4_toolchains//:cmake-3.24.4-linux-aarch64_toolchain",
                "@cmake_3.24.4_toolchains//:cmake-3.24.4-linux-x86_64_toolchain",
                "@cmake_3.24.4_toolchains//:cmake-3.24.4-macos-universal_toolchain",
                "@cmake_3.24.4_toolchains//:cmake-3.24.4-windows-i386_toolchain",
                "@cmake_3.24.4_toolchains//:cmake-3.24.4-windows-x86_64_toolchain",
            )

        return

    if "3.23.x" == version or "3.23.5" == version:
        maybe(
            http_archive,
            name = "cmake-3.23.5-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-aarch64.tar.gz",
            ],
            sha256 = "dcf25a81de6bd4e646389a0635b050ed04d0f27e4f07ae22d975391f38f3c4b8",
            strip_prefix = "cmake-3.23.5-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.23.5-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-x86_64.tar.gz",
            ],
            sha256 = "bbd7ad93d2a14ed3608021a9466ae63db76a24efd1fae7a5f7798c1de7ab9344",
            strip_prefix = "cmake-3.23.5-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.23.5-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-macos-universal.tar.gz",
            ],
            sha256 = "245f07d6e346d2b3fdda600b3705579cf956fdd82ac4f4326b96e7d2c43a9312",
            strip_prefix = "cmake-3.23.5-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.23.5-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-i386.zip",
            ],
            sha256 = "ac454a9bcdfad932c8658c864c239506b2b2ebaf88b75ff96bc27a672f8ce7f9",
            strip_prefix = "cmake-3.23.5-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.23.5-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-x86_64.zip",
            ],
            sha256 = "51c75f93ebfe295701df205e5e78808b1e707996b26b5c26c3f680ab7b543881",
            strip_prefix = "cmake-3.23.5-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.23.5_toolchains",
            repos = {
                "cmake-3.23.5-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.23.5-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.23.5-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.23.5-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.23.5-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.23.5_toolchains//:cmake-3.23.5-linux-aarch64_toolchain",
                "@cmake_3.23.5_toolchains//:cmake-3.23.5-linux-x86_64_toolchain",
                "@cmake_3.23.5_toolchains//:cmake-3.23.5-macos-universal_toolchain",
                "@cmake_3.23.5_toolchains//:cmake-3.23.5-windows-i386_toolchain",
                "@cmake_3.23.5_toolchains//:cmake-3.23.5-windows-x86_64_toolchain",
            )

        return

    if "3.22.x" == version or "3.22.6" == version:
        maybe(
            http_archive,
            name = "cmake-3.22.6-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-aarch64.tar.gz",
            ],
            sha256 = "79be85d3e76565faacd60695cee11d030f7e7dd8691476144fa25eb93dbd0397",
            strip_prefix = "cmake-3.22.6-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.22.6-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-x86_64.tar.gz",
            ],
            sha256 = "09e1b34026c406c5bf4d1b053eadb3a8519cb360e37547ebf4b70ab766d94fbc",
            strip_prefix = "cmake-3.22.6-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.22.6-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-macos-universal.tar.gz",
            ],
            sha256 = "b4569e10b0f86ed4fad23aae879a197de6fb14aca057bfc2e3baf236c3e876c5",
            strip_prefix = "cmake-3.22.6-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.22.6-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-i386.zip",
            ],
            sha256 = "058572b13af626e48cc8cba235c14491117b761354fb3c567b11c29835ff8283",
            strip_prefix = "cmake-3.22.6-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.22.6-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-x86_64.zip",
            ],
            sha256 = "48bcc3e71e918b72e2682f9ca9d44dd6c416379071c1ecb530d0633374f91f15",
            strip_prefix = "cmake-3.22.6-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.22.6_toolchains",
            repos = {
                "cmake-3.22.6-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.22.6-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.22.6-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.22.6-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.22.6-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.22.6_toolchains//:cmake-3.22.6-linux-aarch64_toolchain",
                "@cmake_3.22.6_toolchains//:cmake-3.22.6-linux-x86_64_toolchain",
                "@cmake_3.22.6_toolchains//:cmake-3.22.6-macos-universal_toolchain",
                "@cmake_3.22.6_toolchains//:cmake-3.22.6-windows-i386_toolchain",
                "@cmake_3.22.6_toolchains//:cmake-3.22.6-windows-x86_64_toolchain",
            )

        return

    if "3.21.x" == version or "3.21.7" == version:
        maybe(
            http_archive,
            name = "cmake-3.21.7-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-aarch64.tar.gz",
            ],
            sha256 = "fa7e82170391c71dcc958ff57a63e9d6be9742a8b85a8b1386da9e571980474a",
            strip_prefix = "cmake-3.21.7-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.21.7-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-x86_64.tar.gz",
            ],
            sha256 = "f84e209d903a96e54f398bb8760693969b13fc50bce2f8278a9ee9dca01406b2",
            strip_prefix = "cmake-3.21.7-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.21.7-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-macos-universal.tar.gz",
            ],
            sha256 = "3c968c5877a99a801ea30ff3edd3f5a42e10fb715bef295ba611e62c50a2e87c",
            strip_prefix = "cmake-3.21.7-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.21.7-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-i386.zip",
            ],
            sha256 = "a1df7917fd649638d030afe045c1e2cb3df783568f130575cfc04502072955a5",
            strip_prefix = "cmake-3.21.7-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.21.7-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-x86_64.zip",
            ],
            sha256 = "4c4840e2dc2bf82e8a16081ff506bba54f3a228b91ce36317129fed4035ef2e3",
            strip_prefix = "cmake-3.21.7-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.21.7_toolchains",
            repos = {
                "cmake-3.21.7-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.21.7-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.21.7-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.21.7-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.21.7-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.21.7_toolchains//:cmake-3.21.7-linux-aarch64_toolchain",
                "@cmake_3.21.7_toolchains//:cmake-3.21.7-linux-x86_64_toolchain",
                "@cmake_3.21.7_toolchains//:cmake-3.21.7-macos-universal_toolchain",
                "@cmake_3.21.7_toolchains//:cmake-3.21.7-windows-i386_toolchain",
                "@cmake_3.21.7_toolchains//:cmake-3.21.7-windows-x86_64_toolchain",
            )

        return

    if "3.20.x" == version or "3.20.6" == version:
        maybe(
            http_archive,
            name = "cmake-3.20.6-linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-aarch64.tar.gz",
            ],
            sha256 = "9ac2035174d3c62827c85fb052372d70cf35fb565e8d47b8241fbe451c29b2f2",
            strip_prefix = "cmake-3.20.6-linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.20.6-linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-x86_64.tar.gz",
            ],
            sha256 = "458777097903b0f35a0452266b923f0a2f5b62fe331e636e2dcc4b636b768e36",
            strip_prefix = "cmake-3.20.6-linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.20.6-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-macos-universal.tar.gz",
            ],
            sha256 = "bc75cfbcbd95851d2e712c884de80814d7a7939441612af0ae6c5ccc2d94929f",
            strip_prefix = "cmake-3.20.6-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.20.6-windows-i386",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-i386.zip",
            ],
            sha256 = "3166300cce9336cd6d9c468fcb8421086baf1c3f0821bddf5f37703d00adb1cd",
            strip_prefix = "cmake-3.20.6-windows-i386",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.20.6-windows-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-x86_64.zip",
            ],
            sha256 = "f240a38c964712aac474644b3ba21bdc2b4e8d5e31179f67bd2e6f45fa349419",
            strip_prefix = "cmake-3.20.6-windows-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.20.6_toolchains",
            repos = {
                "cmake-3.20.6-linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.20.6-linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.20.6-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.20.6-windows-i386": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.20.6-windows-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.20.6_toolchains//:cmake-3.20.6-linux-aarch64_toolchain",
                "@cmake_3.20.6_toolchains//:cmake-3.20.6-linux-x86_64_toolchain",
                "@cmake_3.20.6_toolchains//:cmake-3.20.6-macos-universal_toolchain",
                "@cmake_3.20.6_toolchains//:cmake-3.20.6-windows-i386_toolchain",
                "@cmake_3.20.6_toolchains//:cmake-3.20.6-windows-x86_64_toolchain",
            )

        return

    if "3.19.x" == version or "3.19.8" == version:
        maybe(
            http_archive,
            name = "cmake-3.19.8-Linux-aarch64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-aarch64.tar.gz",
            ],
            sha256 = "807f5afb2a560e00af9640e496d5673afefc2888bf0ed076412884a5ebb547a1",
            strip_prefix = "cmake-3.19.8-Linux-aarch64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.19.8-Linux-x86_64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-x86_64.tar.gz",
            ],
            sha256 = "db0d7d225150dd6e08ce54995e671f9b4801b8e93e22df1eef52339f6bbbecd9",
            strip_prefix = "cmake-3.19.8-Linux-x86_64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.19.8-macos-universal",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-macos-universal.tar.gz",
            ],
            sha256 = "0976d23d982af05dcbfb3aa34fcb62ead43bea27f0e3bb95222f2a78161423f2",
            strip_prefix = "cmake-3.19.8-macos-universal/CMake.app/Contents",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.19.8-win32-x86",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win32-x86.zip",
            ],
            sha256 = "f82bbfc56fe1c9f9f137991f742d09b79ec31168ef99eb67f8f4fa92276d9efb",
            strip_prefix = "cmake-3.19.8-win32-x86",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        maybe(
            http_archive,
            name = "cmake-3.19.8-win64-x64",
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win64-x64.zip",
            ],
            sha256 = "2a30877a3d6b50da305b289f4d1c03befdfaeb2edba02a563c681e883d810380",
            strip_prefix = "cmake-3.19.8-win64-x64",
            build_file_content = _CMAKE_BUILD_FILE.format(
                bin = "cmake.exe",
                env = {"CMAKE": "$(execpath :cmake_bin)"},
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "cmake_3.19.8_toolchains",
            repos = {
                "cmake-3.19.8-Linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "cmake-3.19.8-Linux-x86_64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "cmake-3.19.8-macos-universal": [
                    "@platforms//os:macos",
                ],
                "cmake-3.19.8-win32-x86": [
                    "@platforms//cpu:x86_32",
                    "@platforms//os:windows",
                ],
                "cmake-3.19.8-win64-x64": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "cmake",
        )

        if register_toolchains:
            native.register_toolchains(
                "@cmake_3.19.8_toolchains//:cmake-3.19.8-Linux-aarch64_toolchain",
                "@cmake_3.19.8_toolchains//:cmake-3.19.8-Linux-x86_64_toolchain",
                "@cmake_3.19.8_toolchains//:cmake-3.19.8-macos-universal_toolchain",
                "@cmake_3.19.8_toolchains//:cmake-3.19.8-win32-x86_toolchain",
                "@cmake_3.19.8_toolchains//:cmake-3.19.8-win64-x64_toolchain",
            )

        return

    fail("Unsupported version: " + str(version))

def _ninja_toolchains(version, register_toolchains):
    if "1.13.x" == version or "1.13.2" == version:
        maybe(
            http_archive,
            name = "ninja_1.13.2_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip",
            ],
            sha256 = "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.13.2_linux-aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux-aarch64.zip",
            ],
            sha256 = "fd2cacc8050a7f12a16a2e48f9e06fca5c14fc4c2bee2babb67b58be17a607fc",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.13.2_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            sha256 = "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.13.2_mac_aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            sha256 = "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.13.2_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip",
            ],
            sha256 = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.13.2_toolchains",
            repos = {
                "ninja_1.13.2_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.13.2_linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "ninja_1.13.2_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.13.2_mac_aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:macos",
                ],
                "ninja_1.13.2_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.13.2_toolchains//:ninja_1.13.2_linux_toolchain",
                "@ninja_1.13.2_toolchains//:ninja_1.13.2_linux-aarch64_toolchain",
                "@ninja_1.13.2_toolchains//:ninja_1.13.2_mac_toolchain",
                "@ninja_1.13.2_toolchains//:ninja_1.13.2_mac_aarch64_toolchain",
                "@ninja_1.13.2_toolchains//:ninja_1.13.2_win_toolchain",
            )

        return

    if "1.12.x" == version or "1.12.1" == version:
        maybe(
            http_archive,
            name = "ninja_1.12.1_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip",
            ],
            sha256 = "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.12.1_linux-aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux-aarch64.zip",
            ],
            sha256 = "5c25c6570b0155e95fce5918cb95f1ad9870df5768653afe128db822301a05a1",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.12.1_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.12.1_mac_aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.12.1_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip",
            ],
            sha256 = "f550fec705b6d6ff58f2db3c374c2277a37691678d6aba463adcbb129108467a",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.12.1_toolchains",
            repos = {
                "ninja_1.12.1_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.12.1_linux-aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:linux",
                ],
                "ninja_1.12.1_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.12.1_mac_aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:macos",
                ],
                "ninja_1.12.1_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.12.1_toolchains//:ninja_1.12.1_linux_toolchain",
                "@ninja_1.12.1_toolchains//:ninja_1.12.1_linux-aarch64_toolchain",
                "@ninja_1.12.1_toolchains//:ninja_1.12.1_mac_toolchain",
                "@ninja_1.12.1_toolchains//:ninja_1.12.1_mac_aarch64_toolchain",
                "@ninja_1.12.1_toolchains//:ninja_1.12.1_win_toolchain",
            )

        return

    if "1.11.x" == version or "1.11.1" == version:
        maybe(
            http_archive,
            name = "ninja_1.11.1_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip",
            ],
            sha256 = "b901ba96e486dce377f9a070ed4ef3f79deb45f4ffe2938f8e7ddc69cfb3df77",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.11.1_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            sha256 = "482ecb23c59ae3d4f158029112de172dd96bb0e97549c4b1ca32d8fad11f873e",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.11.1_mac_aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            sha256 = "482ecb23c59ae3d4f158029112de172dd96bb0e97549c4b1ca32d8fad11f873e",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.11.1_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip",
            ],
            sha256 = "524b344a1a9a55005eaf868d991e090ab8ce07fa109f1820d40e74642e289abc",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.11.1_toolchains",
            repos = {
                "ninja_1.11.1_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.11.1_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.11.1_mac_aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:macos",
                ],
                "ninja_1.11.1_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.11.1_toolchains//:ninja_1.11.1_linux_toolchain",
                "@ninja_1.11.1_toolchains//:ninja_1.11.1_mac_toolchain",
                "@ninja_1.11.1_toolchains//:ninja_1.11.1_mac_aarch64_toolchain",
                "@ninja_1.11.1_toolchains//:ninja_1.11.1_win_toolchain",
            )

        return

    if "1.10.x" == version or "1.10.2" == version:
        maybe(
            http_archive,
            name = "ninja_1.10.2_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip",
            ],
            sha256 = "763464859c7ef2ea3a0a10f4df40d2025d3bb9438fcb1228404640410c0ec22d",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.10.2_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            sha256 = "6fa359f491fac7e5185273c6421a000eea6a2f0febf0ac03ac900bd4d80ed2a5",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.10.2_mac_aarch64",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            sha256 = "6fa359f491fac7e5185273c6421a000eea6a2f0febf0ac03ac900bd4d80ed2a5",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.10.2_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip",
            ],
            sha256 = "bbde850d247d2737c5764c927d1071cbb1f1957dcabda4a130fa8547c12c695f",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.10.2_toolchains",
            repos = {
                "ninja_1.10.2_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.10.2_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.10.2_mac_aarch64": [
                    "@platforms//cpu:aarch64",
                    "@platforms//os:macos",
                ],
                "ninja_1.10.2_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.10.2_toolchains//:ninja_1.10.2_linux_toolchain",
                "@ninja_1.10.2_toolchains//:ninja_1.10.2_mac_toolchain",
                "@ninja_1.10.2_toolchains//:ninja_1.10.2_mac_aarch64_toolchain",
                "@ninja_1.10.2_toolchains//:ninja_1.10.2_win_toolchain",
            )

        return

    if "1.9.x" == version or "1.9.0" == version:
        maybe(
            http_archive,
            name = "ninja_1.9.0_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip",
            ],
            sha256 = "1b1235f2b0b4df55ac6d80bbe681ea3639c9d2c505c7ff2159a3daf63d196305",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.9.0_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip",
            ],
            sha256 = "26d32a79f786cca1004750f59e545199bf110e21e300d3c2424c1fddd78f28ab",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.9.0_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip",
            ],
            sha256 = "2d70010633ddaacc3af4ffbd21e22fae90d158674a09e132e06424ba3ab036e9",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.9.0_toolchains",
            repos = {
                "ninja_1.9.0_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.9.0_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.9.0_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.9.0_toolchains//:ninja_1.9.0_linux_toolchain",
                "@ninja_1.9.0_toolchains//:ninja_1.9.0_mac_toolchain",
                "@ninja_1.9.0_toolchains//:ninja_1.9.0_win_toolchain",
            )

        return

    if "1.8.x" == version or "1.8.2" == version:
        maybe(
            http_archive,
            name = "ninja_1.8.2_linux",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip",
            ],
            sha256 = "d2fea9ff33b3ef353161ed906f260d565ca55b8ca0568fa07b1d2cab90a84a07",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.8.2_mac",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip",
            ],
            sha256 = "0347d55c66061652b26f48769d566761630ffde3143793b29064a57f356542cc",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        maybe(
            http_archive,
            name = "ninja_1.8.2_win",
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip",
            ],
            sha256 = "c80313e6c26c0b9e0c241504718e2d8bbc2798b73429933adf03fdc6d84f0e70",
            strip_prefix = "",
            build_file_content = _NINJA_BUILD_FILE.format(
                bin = "ninja.exe",
                env = {"NINJA": "$(execpath :ninja_wrapper_bin)", "REAL_NINJA": "$(execpath :ninja_bin)"},
                wrapper = "@rules_foreign_cc//toolchains/private:ninja_wrapper",
            ),
        )

        # buildifier: leave-alone
        maybe(
            prebuilt_toolchains_repository,
            name = "ninja_1.8.2_toolchains",
            repos = {
                "ninja_1.8.2_linux": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:linux",
                ],
                "ninja_1.8.2_mac": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:macos",
                ],
                "ninja_1.8.2_win": [
                    "@platforms//cpu:x86_64",
                    "@platforms//os:windows",
                ],
            },
            tool = "ninja",
        )

        if register_toolchains:
            native.register_toolchains(
                "@ninja_1.8.2_toolchains//:ninja_1.8.2_linux_toolchain",
                "@ninja_1.8.2_toolchains//:ninja_1.8.2_mac_toolchain",
                "@ninja_1.8.2_toolchains//:ninja_1.8.2_win_toolchain",
            )

        return

    fail("Unsupported version: " + str(version))
