cc_library(
    name = "built_with_bazel",
    srcs = ["builtWithBazel.c"],
    hdrs = [
        "builtWithBazel.h",
        "detail/builtWithBazel.h",
    ],
    visibility = ["//visibility:public"]
)