all:
	rm -f '$(MAKEVARS_FILE)' '$(SHELLVARS_FILE)'
	touch '$(MAKEVARS_FILE)' '$(SHELLVARS_FILE)'
	{{VARIABLES}}
	for filename in '$(MAKEVARS_FILE)' '$(SHELLVARS_FILE)'; do \
		# Note that this is order-sensitive, since INSTALLDIR is a subdir of \
		# EXT_BUILD_ROOT and we want the replacement to be most specific first. \
		sed -i.bak \
			-e 's|$(BUILD_TMPDIR)|{{BUILD_TMPDIR}}|g' \
			-e 's|$(EXT_BUILD_DEPS)|{{EXT_BUILD_DEPS}}|g' \
			-e 's|$(INSTALLDIR)|{{INSTALLDIR}}|g' \
			-e 's|$(EXT_BUILD_ROOT)|{{EXT_BUILD_ROOT}}|g' \
			"$${filename}"; \
	done

.PHONY: all
