#!/usr/bin/env bash

set -euo pipefail

set +u
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -d ' ' -f 2-)" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -d ' ' -f 2-)" 2>/dev/null || {
    echo >&2 "cannot find $f"
    exit 1
  }
set -u

# The runtime manifest is a tab-separated file generated by the test macro.
# It contains one binary name, one list of binary runfile candidates, and zero
# or more expected loaded-library groups.
#
# Example:
#
#   binary_name	app
#   binary	integration_tests/.../case/app integration_tests/.../case/app.exe
#   expect	libarchive	external/.../examples_libarchive/.../bin/archive.dll
#   expect	zlib	external/.../examples_zlib/.../bin/zlib1.dll
#
# `binary` and `expect` path fields may contain multiple space-separated
# runfile paths because they come from Bazel `$(rlocationpaths ...)`.
usage() {
  echo "usage: COREUTILS_RLOCATION_PATH=<path> $0 <runtime-manifest-runfile-path>" >&2
}

is_windows() {
  case "$(uname -s 2>/dev/null || true)" in
    CYGWIN*|MINGW*|MSYS*)
      return 0
      ;;
  esac
  return 1
}

windows_shell_path() {
  if command -v cygpath >/dev/null; then
    cygpath -u "$1"
    return
  fi
  printf '%s\n' "$1"
}

real_file_path() {
  "$coreutils_bin" realpath "$1"
}

runfile_path() {
  local path="$1"
  local resolved

  resolved="$(rlocation "$path")"
  if [[ -z "$resolved" || ! -f "$resolved" ]]; then
    echo "runfile not found: $path" >&2
    exit 1
  fi

  printf '%s\n' "$resolved"
}

canonical_path() {
  local path

  path="$(real_file_path "$1")"
  if is_windows; then
    if command -v cygpath >/dev/null; then
      path="$(cygpath -m "$path")"
    fi
    path="${path//\\//}"
    printf '%s\n' "$path" | tr '[:upper:]' '[:lower:]'
    return
  fi

  printf '%s\n' "$path"
}

shared_library_candidate() {
  case "$(basename "$1")" in
    *.so|*.so.*|*.dylib|*.dll)
      return 0
      ;;
  esac
  return 1
}

resolve_shared_library_runfile() {
  local candidate="$1"
  local resolved_candidate

  if [[ -z "$candidate" ]] || ! shared_library_candidate "$candidate"; then
    return 1
  fi

  resolved_candidate="$(rlocation "$candidate")"
  if [[ -z "$resolved_candidate" || ! -e "$resolved_candidate" ]]; then
    return 1
  fi

  printf '%s\n' "$resolved_candidate"
}

binary_name_matches() {
  local candidate_basename
  candidate_basename="$(basename "$1")"
  if [[ "$candidate_basename" == "$binary_name" ]]; then
    return 0
  fi
  if is_windows && [[ "$candidate_basename" == "${binary_name}.exe" ]]; then
    return 0
  fi
  return 1
}

loaded_path_for() {
  local name="$1"
  local line
  line="$(grep -m1 "^loaded ${name}: " "$stdout_file" || true)"
  if [[ -z "$line" ]]; then
    echo "missing loaded path for ${name}" >&2
    cat "$stdout_file" >&2
    exit 1
  fi
  printf '%s\n' "${line#loaded ${name}: }"
}

# Bazel may load shared libraries through its _solib_* tree even when the
# expected target artifact appears in runfiles at its external repository path.
#
#   loaded:   .../t_test.runfiles/_main/_solib_k8/.../libarchive.so.13
#   expected: .../t_test.runfiles/examples_libarchive/.../libarchive.so.13
#
# Local runfiles usually make those paths converge through symlinks, but Remote
# Build Execution (RBE) can materialize them as separate files. In that case,
# realpath equality is not stable, so accept only matching Bazel solib aliases
# with the same basename and digest as an expected target artifact.
loaded_solib_alias_matches_expected() {
  local loaded_path="$1"
  local expected_path="$2"
  local expected_hash
  local loaded_hash

  case "$loaded_path" in
    */_solib_*/*)
      ;;
    *)
      return 1
      ;;
  esac
  if [[ "$(basename "$loaded_path")" != "$(basename "$expected_path")" ]]; then
    return 1
  fi

  loaded_hash="$("$coreutils_bin" sha256sum "$loaded_path")"
  expected_hash="$("$coreutils_bin" sha256sum "$expected_path")"
  [[ "${loaded_hash%% *}" == "${expected_hash%% *}" ]]
}

assert_loaded_from_expected() {
  local name="$1"
  local candidate_blob="$2"
  local candidate
  local candidate_canonical
  local loaded_path
  local loaded_canonical
  local expected_canonical_paths=()
  local resolved_candidate

  loaded_path="$(loaded_path_for "$name")"
  # app.c prints sentinel values such as `<unresolved>` when it cannot map a
  # symbol back to a loaded shared library, so do not treat that as a real path.
  if [[ "$loaded_path" == \<*\> ]]; then
    echo "${name} did not resolve to a loaded shared library" >&2
    cat "$stdout_file" >&2
    exit 1
  fi
  loaded_canonical="$(canonical_path "$loaded_path")"

  while IFS= read -r candidate; do
    resolved_candidate="$(resolve_shared_library_runfile "$candidate")" || continue
    candidate_canonical="$(canonical_path "$resolved_candidate")"
    expected_canonical_paths+=("$candidate_canonical")
    if [[ "$loaded_canonical" == "$candidate_canonical" ]]; then
      return
    fi
    if loaded_solib_alias_matches_expected "$loaded_path" "$resolved_candidate"; then
      return
    fi
  done <<< "$candidate_blob"

  echo "${name} loaded from unexpected path" >&2
  echo "actual: $loaded_canonical" >&2
  echo "expected one of:" >&2
  printf '  %s\n' "${expected_canonical_paths[@]}" >&2
  exit 1
}

append_windows_dll_search_dir() {
  local candidate_dir="$1"
  local candidate_dir_path

  if [[ ! -d "$candidate_dir" ]]; then
    return
  fi

  candidate_dir_path="$(windows_shell_path "$candidate_dir")"
  case ":$windows_dll_search_path:" in
    *":$candidate_dir_path:"*)
      ;;
    *)
      if [[ -n "$windows_dll_search_path" ]]; then
        windows_dll_search_path+=":"
      fi
      windows_dll_search_path+="$candidate_dir_path"
      ;;
  esac
}

append_windows_dll_search_dirs() {
  local candidate_blob="$1"
  local candidate
  local resolved_candidate
  local candidate_dir

  while IFS= read -r candidate; do
    resolved_candidate="$(resolve_shared_library_runfile "$candidate")" || continue
    resolved_candidate="$(real_file_path "$resolved_candidate")"
    candidate_dir="$(dirname "$resolved_candidate")"
    append_windows_dll_search_dir "$candidate_dir"
  done <<< "$candidate_blob"
}

if [[ "$#" -ne 1 ]]; then
  usage
  exit 1
fi

manifest_runfile_path="$1"
manifest="$(runfile_path "$manifest_runfile_path")"

if [[ -z "${COREUTILS_RLOCATION_PATH:-}" ]]; then
  echo "COREUTILS_RLOCATION_PATH is not set" >&2
  exit 1
fi

coreutils_bin="$(runfile_path "$COREUTILS_RLOCATION_PATH")"

binary_name=""
binary_candidates=()
expected_names=()
expected_candidate_blobs=()

while IFS=$'\t' read -r record name paths; do
  words=()
  case "$record" in
    "")
      ;;
    binary_name)
      binary_name="$name"
      ;;
    binary)
      read -r -a words <<< "$name"
      binary_candidates+=("${words[@]}")
      ;;
    expect)
      read -r -a words <<< "${paths:-}"
      expected_candidate_blob="$(printf '%s\n' "${words[@]}")"
      if [[ -z "$name" || -z "$expected_candidate_blob" ]]; then
        echo "invalid expect record in runtime manifest: $record $name ${paths:-}" >&2
        exit 1
      fi
      expected_names+=("$name")
      expected_candidate_blobs+=("$expected_candidate_blob")
      ;;
    *)
      echo "unknown runtime manifest record: $record" >&2
      exit 1
      ;;
  esac
done < "$manifest"

if [[ -z "$binary_name" ]]; then
  echo "runtime manifest missing binary_name record" >&2
  exit 1
fi
if [[ "${#binary_candidates[@]}" -eq 0 ]]; then
  echo "runtime manifest missing binary record" >&2
  exit 1
fi

binary_runfile_path=""
for candidate in "${binary_candidates[@]}"; do
  if binary_name_matches "$candidate"; then
    binary_runfile_path="$candidate"
    break
  fi
done

if [[ -z "$binary_runfile_path" ]]; then
  echo "$binary_name runfile path not found in: ${binary_candidates[*]}" >&2
  exit 1
fi

binary="$(rlocation "$binary_runfile_path")"
if [[ -z "$binary" || ! -f "$binary" ]]; then
  echo "$binary_name is not executable: $binary_runfile_path" >&2
  exit 1
fi
if ! is_windows && [[ ! -x "$binary" ]]; then
  echo "$binary_name is not executable: $binary_runfile_path" >&2
  exit 1
fi

stdout_file="$TEST_TMPDIR/transitive-matrix-stdout.txt"
stderr_file="$TEST_TMPDIR/transitive-matrix-stderr.txt"

set +e
if is_windows; then
  # Windows resolves imported DLLs by searching the executable directory,
  # system locations, then PATH; it does not honor ELF/Mach-O rpath. In Bazel
  # runfiles, dependency DLLs can live in separate output directories instead
  # of beside the test binary, so prepend the expected Bazel-built DLL
  # directories to PATH before launching it. Prepending keeps ambient PATH
  # entries from winning when they contain a DLL with the same basename.
  #
  # Example: the test binary may be in `.../case/`, while expected DLLs are in
  # `.../examples_libarchive/.../bin/archive.dll` and
  # `.../examples_zlib/.../bin/zlib1.dll`. The manifest lists those DLL files.
  # This loop resolves them, adds their parent `bin` directories to PATH, then
  # runs the binary. The app prints the actual loaded DLL paths, and the final
  # assertions check they match the manifest files.
  windows_dll_search_path=""
  for index in "${!expected_candidate_blobs[@]}"; do
    append_windows_dll_search_dirs "${expected_candidate_blobs[$index]}"
  done
  windows_child_path="$windows_dll_search_path"
  if [[ -n "$windows_child_path" && -n "${PATH:-}" ]]; then
    windows_child_path+=":"
  fi
  windows_child_path+="${PATH:-}"
  PATH="$windows_child_path" "$binary" >"$stdout_file" 2>"$stderr_file"
else
  env -u LD_LIBRARY_PATH -u DYLD_LIBRARY_PATH "$binary" >"$stdout_file" 2>"$stderr_file"
fi
status="$?"
set -e

if [[ "$status" -ne 0 ]]; then
  echo "$binary_name failed with exit code $status: $binary" >&2
  if is_windows; then
    echo "windows dll search path: ${windows_dll_search_path:-<empty>}" >&2
  fi
  cat "$stdout_file" >&2
  cat "$stderr_file" >&2
  exit "$status"
fi

expected="expected libarchive+zlib loaded: payload=rules_foreign_cc_transitive_test"
if ! grep -Fxq "$expected" "$stdout_file"; then
  echo "unexpected transitive matrix output" >&2
  echo "expected: $expected" >&2
  echo "actual:" >&2
  cat "$stdout_file" >&2
  cat "$stderr_file" >&2
  exit 1
fi

for index in "${!expected_names[@]}"; do
  assert_loaded_from_expected \
    "${expected_names[$index]}" \
    "${expected_candidate_blobs[$index]}"
done
