workspace(name = "make_luajit")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

local_repository(
    name = "rules_foreign_cc",
    path = "../..",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies(register_default_tools = True)

http_archive(
    name = "postgresql",
    build_file_content = all_content,
    sha256 = "8808449444ee9b086054a6dcfbfb98029e4f8022372c2edf3de5b6d8f417c8e4",
    strip_prefix = "postgresql-12.2",
    urls = [
        "https://ftp.postgresql.org/pub/source/v12.2/postgresql-12.2.tar.gz",
    ],
)
