"""@generated by toolchains/prebuilt_toolchains.py — do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

CMAKE_BIN_SRCS = {
    "3.19.8": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-Linux-aarch64",
            sha256 = "807f5afb2a560e00af9640e496d5673afefc2888bf0ed076412884a5ebb547a1",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "Linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-Linux-x86_64",
            sha256 = "db0d7d225150dd6e08ce54995e671f9b4801b8e93e22df1eef52339f6bbbecd9",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "Linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-macos-universal/CMake.app/Contents",
            sha256 = "0976d23d982af05dcbfb3aa34fcb62ead43bea27f0e3bb95222f2a78161423f2",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win32-x86.zip",
            ],
            strip_prefix = "cmake-3.19.8-win32-x86",
            sha256 = "f82bbfc56fe1c9f9f137991f742d09b79ec31168ef99eb67f8f4fa92276d9efb",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "win32-x86",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win64-x64.zip",
            ],
            strip_prefix = "cmake-3.19.8-win64-x64",
            sha256 = "2a30877a3d6b50da305b289f4d1c03befdfaeb2edba02a563c681e883d810380",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "win64-x64",
        ),
    },
    "3.20.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-linux-aarch64",
            sha256 = "9ac2035174d3c62827c85fb052372d70cf35fb565e8d47b8241fbe451c29b2f2",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-linux-x86_64",
            sha256 = "458777097903b0f35a0452266b923f0a2f5b62fe331e636e2dcc4b636b768e36",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-macos-universal/CMake.app/Contents",
            sha256 = "bc75cfbcbd95851d2e712c884de80814d7a7939441612af0ae6c5ccc2d94929f",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.20.6-windows-i386",
            sha256 = "3166300cce9336cd6d9c468fcb8421086baf1c3f0821bddf5f37703d00adb1cd",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.20.6-windows-x86_64",
            sha256 = "f240a38c964712aac474644b3ba21bdc2b4e8d5e31179f67bd2e6f45fa349419",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.21.7": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-linux-aarch64",
            sha256 = "fa7e82170391c71dcc958ff57a63e9d6be9742a8b85a8b1386da9e571980474a",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-linux-x86_64",
            sha256 = "f84e209d903a96e54f398bb8760693969b13fc50bce2f8278a9ee9dca01406b2",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-macos-universal/CMake.app/Contents",
            sha256 = "3c968c5877a99a801ea30ff3edd3f5a42e10fb715bef295ba611e62c50a2e87c",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.21.7-windows-i386",
            sha256 = "a1df7917fd649638d030afe045c1e2cb3df783568f130575cfc04502072955a5",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.21.7-windows-x86_64",
            sha256 = "4c4840e2dc2bf82e8a16081ff506bba54f3a228b91ce36317129fed4035ef2e3",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.22.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-linux-aarch64",
            sha256 = "79be85d3e76565faacd60695cee11d030f7e7dd8691476144fa25eb93dbd0397",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-linux-x86_64",
            sha256 = "09e1b34026c406c5bf4d1b053eadb3a8519cb360e37547ebf4b70ab766d94fbc",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-macos-universal/CMake.app/Contents",
            sha256 = "b4569e10b0f86ed4fad23aae879a197de6fb14aca057bfc2e3baf236c3e876c5",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.22.6-windows-i386",
            sha256 = "058572b13af626e48cc8cba235c14491117b761354fb3c567b11c29835ff8283",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.22.6-windows-x86_64",
            sha256 = "48bcc3e71e918b72e2682f9ca9d44dd6c416379071c1ecb530d0633374f91f15",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.23.5": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-linux-aarch64",
            sha256 = "dcf25a81de6bd4e646389a0635b050ed04d0f27e4f07ae22d975391f38f3c4b8",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-linux-x86_64",
            sha256 = "bbd7ad93d2a14ed3608021a9466ae63db76a24efd1fae7a5f7798c1de7ab9344",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-macos-universal/CMake.app/Contents",
            sha256 = "245f07d6e346d2b3fdda600b3705579cf956fdd82ac4f4326b96e7d2c43a9312",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.23.5-windows-i386",
            sha256 = "ac454a9bcdfad932c8658c864c239506b2b2ebaf88b75ff96bc27a672f8ce7f9",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.23.5-windows-x86_64",
            sha256 = "51c75f93ebfe295701df205e5e78808b1e707996b26b5c26c3f680ab7b543881",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.24.4": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-linux-aarch64",
            sha256 = "86f823f2636bf715af89da10e04daa476755a799d451baee66247846e95d7bee",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-linux-x86_64",
            sha256 = "cac77d28fb8668c179ac02c283b058aeb846fe2133a57d40b503711281ed9f19",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-macos-universal/CMake.app/Contents",
            sha256 = "16f68724ccd6c2e63e803d3d1dbc2961e5c84d3e123a7bf91825515d750eeac6",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.24.4-windows-i386",
            sha256 = "2839c1286e5a5f08316fc608af4911f7262cd50a166146bf561f2eec49ef2cd6",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.24.4-windows-x86_64",
            sha256 = "c135c7ab78143c46e6686b1e9652bc1dd07e0cf71fd4decee777cdca77019c39",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.25.3": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-linux-aarch64",
            sha256 = "cd6e853639f858569e22e6298f009eb24b4702c51c0d5bc1cb36c688f7ce246d",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-linux-x86_64",
            sha256 = "d4d2ba83301b215857d3b6590cd4434a414fa151c5807693abe587bd6c03581e",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-macos-universal/CMake.app/Contents",
            sha256 = "771548ed2abae17f3fd28dcfa572ba3fe9f970652a72c36c2e1aafdee93a234e",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.25.3-windows-i386",
            sha256 = "2e66cf7cbd35f392f6b9406910c68f4adfca1de9ab7a2fc4cec658c5c5cd9190",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.25.3-windows-x86_64",
            sha256 = "d129425d569140b729210f3383c246dec19c4183f7d0afae1837044942da3b4b",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.26.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-linux-aarch64",
            sha256 = "7b91a212b9e8ca38c1482ae40ff2d3e33e9d1c7b337b39f74bd4f34fd070bb1d",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-linux-x86_64",
            sha256 = "2dd48ccd3e3d872ee4cc916f3f4e24812612421007e895f82bf9fc7e49831d62",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-macos-universal/CMake.app/Contents",
            sha256 = "2d7a4e5f48ad23ef962b5b7c602c4b0163dd44e51b6d4c33b336a1d663ab1445",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.26.6-windows-i386",
            sha256 = "dc3f535d880d1ffa7cfa86a0eefdc1fc9bf8b9ede59d1deb7a2bb41f0a58d2d4",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.26.6-windows-x86_64",
            sha256 = "07b1c4cae3182ca1782a4d9775b5e5d164b475eb010e1dd98ce0c206c38fa73d",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.27.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-linux-aarch64",
            sha256 = "11bf3d30697df465cdf43664a9473a586f010c528376a966fd310a3a22082461",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-linux-x86_64",
            sha256 = "72b01478eeb312bf1a0136208957784fe55a7b587f8d9f9142a7fc9b0b9e9a28",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-macos-universal/CMake.app/Contents",
            sha256 = "ae1fdfd3f74864d0432f2e4a93ff6488125cd8f2869a40a1c2d5166feb6c607c",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.27.9-windows-i386",
            sha256 = "7296b5a46eb53bfd0e0ff1d818067745cb831ab8d3cef9d266bfc842a435d515",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.27.9-windows-x86_64",
            sha256 = "c14e8b5d1c7be0baf0e7936ce8b5a39c5ee3450b14d7e3b32435083eddd9aff7",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.28.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-linux-aarch64",
            sha256 = "7909cc2128ce9442c63ce674a0bfb0e4f4ce04cef667d887e15ad5670d594ba7",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-linux-x86_64",
            sha256 = "931e3c0d546ee03ca72bb147ccd9b49e3b6252f765f66bf21b9d165519940458",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-macos-universal/CMake.app/Contents",
            sha256 = "e992f382a98839aefc9292142699af5d43952e3087509d7671aef0dbeb33e852",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.28.6-windows-i386",
            sha256 = "29503bc5525592c95a51a0f58eea9a9e38650dbbe7bbeb1caab7fc8f4048d7c5",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.28.6-windows-x86_64",
            sha256 = "a8f2e684ead94a64fd3517a38857a5b3f7f8d68d15c49ca1143d18797eaf9cac",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.29.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-linux-aarch64",
            sha256 = "3fc32b2c0701b16d42db5e5062bdb6bf5b6ef831278535ee5946793fa4460954",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-linux-x86_64",
            sha256 = "dd433a0d9babf08cbd79eac319c06b8287929ad88ff8c1b83cbc6cfd5ea90acc",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-macos-universal/CMake.app/Contents",
            sha256 = "4502ccc9f9eb9e7bf495666b637a9e63a695537b0d0850c1ca0ebcc61c5149e5",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.29.9-windows-i386",
            sha256 = "70556ace59d1651fcc40a1712d9a6d900791cc21235ece7158ca7244410c1005",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.29.9-windows-x86_64",
            sha256 = "7858d849d4061b0684366a81701a9b2bad2d3c332a40cc67cf11eef40c08fddb",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.30.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-linux-aarch64",
            sha256 = "9ae2b709ed3aaef504dd25fb6abe7dd4df68cd46824e45d7ee89ae57951d215a",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-linux-x86_64",
            sha256 = "9114e33358a9efc93d6ea658805280fc3201b882b944a4d946edd9472fd1eec7",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-macos-universal/CMake.app/Contents",
            sha256 = "572bf27e2e98d7513e0835525a2b9dc0f3947f6ad7494615e22b60369e87db11",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.30.9-windows-i386",
            sha256 = "0ec7d45b8705f019015dca50603600bb68407201f94205f3cba6d1004da5c086",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.30.9-windows-x86_64",
            sha256 = "b60b316b4827852b3f49f3a6e35e1a9c2301f8c2dca81d135ba0731d4fd9338b",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "3.31.12": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-linux-aarch64",
            sha256 = "83f8fd91d2038a56556e1400390fcfe42f79602940c494f6c6f1cdae7f9e7f40",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-linux-x86_64",
            sha256 = "0dc2e9a6860f06bf10bd8fadc03e35d9eeb4df46e33763a7e480e987758f385c",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-macos-universal/CMake.app/Contents",
            sha256 = "799af7fd545db9bf1b9cfe72f8095880e727a2d4e0df0e3dffc3bc7b95c2d3b0",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.31.12-windows-i386",
            sha256 = "722c3b553e18e8bb1a038474b4d7c52159c00a37b5e04091434507ccd4ce162c",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.31.12-windows-x86_64",
            sha256 = "0c4baa40f28b3f8225eb3fdf6946c987b4fe901403b4eaf2fbbd9378100aaa0c",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
    "4.0.7": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-linux-aarch64",
            sha256 = "ad77fb21981b774f5d33b5ec0987071d93fee1d080599f7f61e59545f4cb0b50",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-linux-x86_64",
            sha256 = "dba36a8e7898e02c3a66dbe169dc776ffc81c2ee6d5bcab3c526d3f3976b4e91",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
            plat_target = "linux-x86_64",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-macos-universal/CMake.app/Contents",
            sha256 = "dba00f8ad22a832dad0f6754e62384780684a4c9d127de472fb0e92df719f1c4",
            integrity = "",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
            plat_target = "macos-universal",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-i386.zip",
            ],
            strip_prefix = "cmake-4.0.7-windows-i386",
            sha256 = "d1252c83ccf19511ae5ed54497b8488fd9b96e0f2b1f7fbb97bfdb55edb9067f",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-i386",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-4.0.7-windows-x86_64",
            sha256 = "3c0bfe3ef9956b39a741afe1385499969bcd100dba7b5076d648bd2fbc56131c",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
            plat_target = "windows-x86_64",
        ),
    },
}

CMAKE_BIN_WILDCARDS = {
    "3.19.x": "3.19.8",
    "3.20.x": "3.20.6",
    "3.21.x": "3.21.7",
    "3.22.x": "3.22.6",
    "3.23.x": "3.23.5",
    "3.24.x": "3.24.4",
    "3.25.x": "3.25.3",
    "3.26.x": "3.26.6",
    "3.27.x": "3.27.9",
    "3.28.x": "3.28.6",
    "3.29.x": "3.29.9",
    "3.30.x": "3.30.9",
    "3.31.x": "3.31.12",
    "4.0.x": "4.0.7",
}
