"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

CMAKE_BIN_SRCS = {
    "3.19.8": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-Linux-aarch64",
            sha256 = "",
            integrity = "sha256-gH9a+ypWDgCvlkDkltVnOv78KIi/DtB2QSiEpeu1R6E=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-Linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-Linux-x86_64",
            sha256 = "",
            integrity = "sha256-2w19IlFQ3W4IzlSZXmcfm0gBuOk+It8e71Izn2u77Nk=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.19.8-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-CXbSPZgq8F3L+zqjT8ti6tQ76ifw47uVIi8qeBYUI/I=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win32-x86.zip",
            ],
            strip_prefix = "cmake-3.19.8-win32-x86",
            sha256 = "",
            integrity = "sha256-+Cu/xW/hyfnxN5kfdC0Jt57DEWjvmetn+PT6kidtnvs=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8-win64-x64.zip",
            ],
            strip_prefix = "cmake-3.19.8-win64-x64",
            sha256 = "",
            integrity = "sha256-KjCHej1rUNowWyifTRwDvv366y7boCpWPGgeiD2BA4A=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.20.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-linux-aarch64",
            sha256 = "",
            integrity = "sha256-msIDUXTTxignyF+wUjctcM81+1ZejUe4JB++RRwpsvI=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-linux-x86_64",
            sha256 = "",
            integrity = "sha256-RYd3CXkDsPNaBFIma5I/Ci9bYv4zHmNuLcxLY2t2jjY=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.20.6-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-vHXPvL2VhR0ucSyITegIFNenk5RBYSrwrmxczC2Ukp8=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.20.6-windows-i386",
            sha256 = "",
            integrity = "sha256-MWYwDM6TNs1tnEaPy4QhCGuvHD8IIb3fXzdwPQCtsc0=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.20.6-windows-x86_64",
            sha256 = "",
            integrity = "sha256-8kCjjJZHEqrEdGRLO6Ib3CtOjV4xF59nvS5vRfo0lBk=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.21.7": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-linux-aarch64",
            sha256 = "",
            integrity = "sha256-+n6CFwORxx3MlY/1emPp1r6XQqi4WosThtqeVxmAR0o=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-linux-x86_64",
            sha256 = "",
            integrity = "sha256-+E4gnZA6luVPOYu4dgaTlpsT/FC84vgnip7p3KAUBrI=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.21.7-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-PJaMWHepmoAeow/z7dP1pC4Q+3Fb7ylbphHmLFCi6Hw=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.21.7-windows-i386",
            sha256 = "",
            integrity = "sha256-od95F/1kljjQMK/gRcHiyz33g1aPEwV1z8BFAgcpVaU=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.21.7-windows-x86_64",
            sha256 = "",
            integrity = "sha256-TEhA4twr+C6KFggf9Qa7pU86IouRzjYxcSn+1ANe8uM=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.22.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-linux-aarch64",
            sha256 = "",
            integrity = "sha256-eb6F0+dlZfqs1gaVzuEdAw9+fdhpFHYUT6JeuT29A5c=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-linux-x86_64",
            sha256 = "",
            integrity = "sha256-CeGzQCbEBsW/TRsFPq2zqFGcs2DjdUfr9LcKt2bZT7w=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.22.6-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-tFaeELD4btT60jquh5oZfeb7FKygV7/C47ryNsPodsU=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.22.6-windows-i386",
            sha256 = "",
            integrity = "sha256-BYVysTr2JuSMyMuiNcFEkRF7dhNU+zxWexHCmDX/goM=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.22.6-windows-x86_64",
            sha256 = "",
            integrity = "sha256-SLzD5x6Ri3LiaC+cqdRN1sQWN5Bxwey1MNBjM3T5HxU=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.23.5": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-linux-aarch64",
            sha256 = "",
            integrity = "sha256-3PJagd5r1OZGOJoGNbBQ7QTQ8n5PB64i2XU5HzjzxLg=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-linux-x86_64",
            sha256 = "",
            integrity = "sha256-u9etk9KhTtNggCGpRmrmPbdqJO/R+uel93mMHeerk0Q=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.23.5-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-JF8H1uNG0rP92mALNwVXnPlW/dgqxPQya5bn0sQ6kxI=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.23.5-windows-i386",
            sha256 = "",
            integrity = "sha256-rEVKm8362TLIZYyGTCOVBrKy66+It1/5a8J6Zy+M5/k=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.23.5-windows-x86_64",
            sha256 = "",
            integrity = "sha256-Ucdfk+v+KVcB3yBeXniAix5weZaya1wmw/aAq3tUOIE=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.24.4": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-linux-aarch64",
            sha256 = "",
            integrity = "sha256-hvgj8mNr9xWvidoQ4E2qR2dVp5nUUbruZiR4Rulde+4=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-linux-x86_64",
            sha256 = "",
            integrity = "sha256-ysd9KPuGaMF5rALCg7BYrrhG/iEzpX1AtQNxEoHtnxk=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.24.4-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-FvaHJMzWwuY+gD09HbwpYeXITT4SOnv5GCVRXXUO6sY=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.24.4-windows-i386",
            sha256 = "",
            integrity = "sha256-KDnBKG5aXwgxb8YIr0kR9yYs1QoWYUa/Vh8u7EnvLNY=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.24.4-windows-x86_64",
            sha256 = "",
            integrity = "sha256-wTXHq3gUPEbmaGsellK8HdB+DPcf1N7O53fNyncBnDk=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.25.3": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-linux-aarch64",
            sha256 = "",
            integrity = "sha256-zW6FNjn4WFaeIuYpjwCesktHAsUcDVvByzbGiPfOJG0=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-linux-x86_64",
            sha256 = "",
            integrity = "sha256-1NK6gzAbIVhX07ZZDNRDSkFPoVHFgHaTq+WHvWwDWB4=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.25.3-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-dxVI7Sq64X8/0o3PpXK6P+n5cGUqcsNsLhqv3uk6I04=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.25.3-windows-i386",
            sha256 = "",
            integrity = "sha256-LmbPfL0185L2uUBpEMaPSt/KHemrei/EzsZYxcXNkZA=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.25.3-windows-x86_64",
            sha256 = "",
            integrity = "sha256-0SlCXVaRQLcpIQ8zg8JG3sGcQYP30K+uGDcESULaO0s=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.26.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-linux-aarch64",
            sha256 = "",
            integrity = "sha256-e5GiErnoyjjBSCrkD/LT4z6dHHszezn3S9TzT9Bwux0=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-linux-x86_64",
            sha256 = "",
            integrity = "sha256-LdSMzT49hy7kzJFvP04kgSYSQhAH6JX4K/n8fkmDHWI=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.26.6-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-LXpOX0itI++WK1t8YCxLAWPdROUbbUwzszah1mOrFEU=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.26.6-windows-i386",
            sha256 = "",
            integrity = "sha256-3D9TXYgNH/p8+oag7v3B/Jv4ue3lnR3reiu0HwpY0tQ=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.26.6-windows-x86_64",
            sha256 = "",
            integrity = "sha256-B7HEyuMYLKF4Kk2XdbXl0WS0desBDh3ZjODCBsOPpz0=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.27.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-linux-aarch64",
            sha256 = "",
            integrity = "sha256-Eb89MGl99GXN9DZkqUc6WG8BDFKDdqlm/TEKOiIIJGE=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-linux-x86_64",
            sha256 = "",
            integrity = "sha256-crAUeO6zEr8aATYgiVd4T+Vae1h/jZ+RQqf8mwuemig=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.27.9-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-rh/f0/dIZNBDLy5Kk/9kiBJc2PKGmkChwtUWb+tsYHw=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.27.9-windows-i386",
            sha256 = "",
            integrity = "sha256-cpa1pG61O/0OD/HYGAZ3RcuDGrjTzvnSZr/IQqQ11RU=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.27.9-windows-x86_64",
            sha256 = "",
            integrity = "sha256-wU6LXRx74Lrw55Ns6LWjnF7jRQsU1+OzJDUIPt3Zr/c=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.28.6": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-linux-aarch64",
            sha256 = "",
            integrity = "sha256-eQnMISjOlELGPOZ0oL+w5PTOBM72Z9iH4VrVZw1ZS6c=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-linux-x86_64",
            sha256 = "",
            integrity = "sha256-kx48DVRu4DynK7FHzNm0njtiUvdl9mvyG50WVRmUBFg=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.28.6-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-6ZLzgqmIOa78kpIUJpmvXUOVLjCHUJ12ca7w2+sz6FI=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.28.6-windows-i386",
            sha256 = "",
            integrity = "sha256-KVA7xVJVkslaUaD1juqanjhlDbvnu+scqrf8j0BI18U=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.28.6-windows-x86_64",
            sha256 = "",
            integrity = "sha256-qPLmhOrZSmT9NRejiFels/f41o0VxJyhFD0YeX6vnKw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.29.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-linux-aarch64",
            sha256 = "",
            integrity = "sha256-P8MrLAcBsW1C215QYr22v1tu+DEnhTXuWUZ5P6RGCVQ=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-linux-x86_64",
            sha256 = "",
            integrity = "sha256-3UM6DZur8Iy9eerDGcBrgoeSmtiP+MG4PLxs/V6pCsw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.29.9-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-RQLMyfnrnnv0lWZrY3qeY6aVU3sNCFDByg68xhxRSeU=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.29.9-windows-i386",
            sha256 = "",
            integrity = "sha256-cFVqzlnRZR/MQKFxLZptkAeRzCEjXs5xWMpyREEMEAU=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.29.9-windows-x86_64",
            sha256 = "",
            integrity = "sha256-eFjYSdQGGwaENmqBcBqbK60tPDMqQMxnzxHu9AwI/ds=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.30.9": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-linux-aarch64",
            sha256 = "",
            integrity = "sha256-muK3Ce06rvUE3SX7ar591N9ozUaCTkXX7omuV5UdIVo=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-linux-x86_64",
            sha256 = "",
            integrity = "sha256-kRTjM1ip78k9bqZYgFKA/DIBuIK5RKTZRu3ZRy/R7sc=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.30.9-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-Vyvyfi6Y11E+CDVSWiudwPOUf2rXSUYV4itgNp6H2xE=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.30.9-windows-i386",
            sha256 = "",
            integrity = "sha256-DsfUW4cF8BkBXcpQYDYAu2hAcgH5QgXzy6bRAE2lwIY=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.30.9-windows-x86_64",
            sha256 = "",
            integrity = "sha256-tgsxa0gnhSs/SfOm414anCMB+MLcqB0TW6BzHU/ZM4s=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "3.31.12": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-linux-aarch64",
            sha256 = "",
            integrity = "sha256-g/j9kdIDilZVbhQAOQ/P5C95YClAxJT2xvHNrn+ef0A=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-linux-x86_64",
            sha256 = "",
            integrity = "sha256-DcLppoYPBr8QvY+twD412e6030bjN2On5IDph3WPOFw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-3.31.12-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-eZr3/VRdub8bnP5y+AlYgOcnotTg3w49/8O8e5XC07A=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-i386.zip",
            ],
            strip_prefix = "cmake-3.31.12-windows-i386",
            sha256 = "",
            integrity = "sha256-ciw7VT4Y6LsaA4R0tNfFIVnACje14ECRQ0UHzNTOFiw=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-3.31.12-windows-x86_64",
            sha256 = "",
            integrity = "sha256-DEuqQPKLP4Il6z/faUbJh7T+kBQDtOry+72TeBAKqgw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
    "4.0.7": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-aarch64.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-linux-aarch64",
            sha256 = "",
            integrity = "sha256-rXf7IZgbd09dM7XsCYcHHZP+4dCAWZ9/YeWVRfTLC1A=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-linux-x86_64.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-linux-x86_64",
            sha256 = "",
            integrity = "sha256-26NqjniY4Cw6Ztvhadx3b/yBwu5tW8qzxSbT85drTpE=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "cmake",
        ),
        ("macos", "universal"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-macos-universal.tar.gz",
            ],
            strip_prefix = "cmake-4.0.7-macos-universal/CMake.app/Contents",
            sha256 = "",
            integrity = "sha256-26APitIqgy2tD2dU5iOEeAaEpMnRJ95HL7DpLfcZ8cQ=",
            constraints = [
                "@platforms//os:macos",
            ],
            bin = "cmake",
        ),
        ("windows", "x86_32"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-i386.zip",
            ],
            strip_prefix = "cmake-4.0.7-windows-i386",
            sha256 = "",
            integrity = "sha256-0SUsg8zxlRGuXtVEl7hIj9m5bg8rH3+7l7/bVe25Bn8=",
            constraints = [
                "@platforms//cpu:x86_32",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7-windows-x86_64.zip",
            ],
            strip_prefix = "cmake-4.0.7-windows-x86_64",
            sha256 = "",
            integrity = "sha256-PAv+PvmVazmnQa/hOFSZlpvNEA26e1B21ki9L7xWExw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "cmake.exe",
        ),
    },
}

CMAKE_BIN_WILDCARDS = {
    "3.19.x": "3.19.8",
    "3.20.x": "3.20.6",
    "3.21.x": "3.21.7",
    "3.22.x": "3.22.6",
    "3.23.x": "3.23.5",
    "3.24.x": "3.24.4",
    "3.25.x": "3.25.3",
    "3.26.x": "3.26.6",
    "3.27.x": "3.27.9",
    "3.28.x": "3.28.6",
    "3.29.x": "3.29.9",
    "3.30.x": "3.30.9",
    "3.31.x": "3.31.12",
    "4.0.x": "4.0.7",
}

CMAKE_SRC_SRCS = {
    "3.19.8": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8.tar.gz",
        ],
        strip_prefix = "cmake-3.19.8",
        sha256 = "",
        integrity = "sha256-CbT6SDeq5Vx1+xcPam4rRIGN66SDNdGWne3fuzTjA2k=",
        patches = [],
    ),
    "3.19.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8.tar.gz",
        ],
        strip_prefix = "cmake-3.19.8",
        sha256 = "",
        integrity = "sha256-CbT6SDeq5Vx1+xcPam4rRIGN66SDNdGWne3fuzTjA2k=",
        patches = [],
    ),
    "3.20.6": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6.tar.gz",
        ],
        strip_prefix = "cmake-3.20.6",
        sha256 = "",
        integrity = "sha256-oL1IXho43RPAuuyJ1fStv2HH/TL92zjqvGmnW8C2XXI=",
        patches = [],
    ),
    "3.20.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6.tar.gz",
        ],
        strip_prefix = "cmake-3.20.6",
        sha256 = "",
        integrity = "sha256-oL1IXho43RPAuuyJ1fStv2HH/TL92zjqvGmnW8C2XXI=",
        patches = [],
    ),
    "3.21.7": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7.tar.gz",
        ],
        strip_prefix = "cmake-3.21.7",
        sha256 = "",
        integrity = "sha256-NSPEpa/GGsPXySg1MBzfCSEpybZypu4X5oyS6SjBN1o=",
        patches = [],
    ),
    "3.21.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.21.7/cmake-3.21.7.tar.gz",
        ],
        strip_prefix = "cmake-3.21.7",
        sha256 = "",
        integrity = "sha256-NSPEpa/GGsPXySg1MBzfCSEpybZypu4X5oyS6SjBN1o=",
        patches = [],
    ),
    "3.22.6": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6.tar.gz",
        ],
        strip_prefix = "cmake-3.22.6",
        sha256 = "",
        integrity = "sha256-c5MxY2cOpOqVwjFUkAewxyQygik1BqLPRENxSCatXsM=",
        patches = [],
    ),
    "3.22.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.22.6/cmake-3.22.6.tar.gz",
        ],
        strip_prefix = "cmake-3.22.6",
        sha256 = "",
        integrity = "sha256-c5MxY2cOpOqVwjFUkAewxyQygik1BqLPRENxSCatXsM=",
        patches = [],
    ),
    "3.23.5": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5.tar.gz",
        ],
        strip_prefix = "cmake-3.23.5",
        sha256 = "",
        integrity = "sha256-8pRM3noUC5krpczqIAmph6kkE3YiUN4i67rOIxmg9H0=",
        patches = [],
    ),
    "3.23.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.23.5/cmake-3.23.5.tar.gz",
        ],
        strip_prefix = "cmake-3.23.5",
        sha256 = "",
        integrity = "sha256-8pRM3noUC5krpczqIAmph6kkE3YiUN4i67rOIxmg9H0=",
        patches = [],
    ),
    "3.24.4": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4.tar.gz",
        ],
        strip_prefix = "cmake-3.24.4",
        sha256 = "",
        integrity = "sha256-MsnkmVEO/3Bw0/Ct+6vgr+ogWGCMX6k+IxvrSfv6IpY=",
        patches = [],
    ),
    "3.24.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4.tar.gz",
        ],
        strip_prefix = "cmake-3.24.4",
        sha256 = "",
        integrity = "sha256-MsnkmVEO/3Bw0/Ct+6vgr+ogWGCMX6k+IxvrSfv6IpY=",
        patches = [],
    ),
    "3.25.3": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3.tar.gz",
        ],
        strip_prefix = "cmake-3.25.3",
        sha256 = "",
        integrity = "sha256-zJlXAdWQym3rxCRemYmTkJnKUoJ91GtdNZLwk6/hkBw=",
        patches = [],
    ),
    "3.25.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3.tar.gz",
        ],
        strip_prefix = "cmake-3.25.3",
        sha256 = "",
        integrity = "sha256-zJlXAdWQym3rxCRemYmTkJnKUoJ91GtdNZLwk6/hkBw=",
        patches = [],
    ),
    "3.26.6": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6.tar.gz",
        ],
        strip_prefix = "cmake-3.26.6",
        sha256 = "",
        integrity = "sha256-BwuaJCLmZtLBQ34tqyOaI26KY2ItCo0P/p44lhPSt2o=",
        patches = [],
    ),
    "3.26.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6.tar.gz",
        ],
        strip_prefix = "cmake-3.26.6",
        sha256 = "",
        integrity = "sha256-BwuaJCLmZtLBQ34tqyOaI26KY2ItCo0P/p44lhPSt2o=",
        patches = [],
    ),
    "3.27.9": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9.tar.gz",
        ],
        strip_prefix = "cmake-3.27.9",
        sha256 = "",
        integrity = "sha256-YJqbmFcqal6kd/kSz/uXMQntTQpqaz+eI1PSzcBIcI4=",
        patches = [],
    ),
    "3.27.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9.tar.gz",
        ],
        strip_prefix = "cmake-3.27.9",
        sha256 = "",
        integrity = "sha256-YJqbmFcqal6kd/kSz/uXMQntTQpqaz+eI1PSzcBIcI4=",
        patches = [],
    ),
    "3.28.6": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6.tar.gz",
        ],
        strip_prefix = "cmake-3.28.6",
        sha256 = "",
        integrity = "sha256-w5xzOQCv/E6w6WiLTRpFQ1pzIQXZv5zB513SubgaNrs=",
        patches = [],
    ),
    "3.28.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.28.6/cmake-3.28.6.tar.gz",
        ],
        strip_prefix = "cmake-3.28.6",
        sha256 = "",
        integrity = "sha256-w5xzOQCv/E6w6WiLTRpFQ1pzIQXZv5zB513SubgaNrs=",
        patches = [],
    ),
    "3.29.9": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9.tar.gz",
        ],
        strip_prefix = "cmake-3.29.9",
        sha256 = "",
        integrity = "sha256-RncBooFlc/h2d0E3nLE48P/0rPNk4V7wsbiHNKx/q1s=",
        patches = [],
    ),
    "3.29.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.29.9/cmake-3.29.9.tar.gz",
        ],
        strip_prefix = "cmake-3.29.9",
        sha256 = "",
        integrity = "sha256-RncBooFlc/h2d0E3nLE48P/0rPNk4V7wsbiHNKx/q1s=",
        patches = [],
    ),
    "3.30.9": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9.tar.gz",
        ],
        strip_prefix = "cmake-3.30.9",
        sha256 = "",
        integrity = "sha256-Zfdlu4fIAZMWyr5ny+Xo9F7eM07rWv0WHKaHTReZTg0=",
        patches = [],
    ),
    "3.30.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.30.9/cmake-3.30.9.tar.gz",
        ],
        strip_prefix = "cmake-3.30.9",
        sha256 = "",
        integrity = "sha256-Zfdlu4fIAZMWyr5ny+Xo9F7eM07rWv0WHKaHTReZTg0=",
        patches = [],
    ),
    "3.31.12": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12.tar.gz",
        ],
        strip_prefix = "cmake-3.31.12",
        sha256 = "",
        integrity = "sha256-Xz/VpU36ZWAr2+1k+YGnJnPMGfLTBMwpVc8N+gz9gnI=",
        patches = [],
    ),
    "3.31.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v3.31.12/cmake-3.31.12.tar.gz",
        ],
        strip_prefix = "cmake-3.31.12",
        sha256 = "",
        integrity = "sha256-Xz/VpU36ZWAr2+1k+YGnJnPMGfLTBMwpVc8N+gz9gnI=",
        patches = [],
    ),
    "4.0.7": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7.tar.gz",
        ],
        strip_prefix = "cmake-4.0.7",
        sha256 = "",
        integrity = "sha256-NWkhF40Bd4LZcBrt0Je1HB6S4YbpQQEeowA5olCdlBc=",
        patches = [],
    ),
    "4.0.x": struct(
        urls = [
            "https://github.com/Kitware/CMake/releases/download/v4.0.7/cmake-4.0.7.tar.gz",
        ],
        strip_prefix = "cmake-4.0.7",
        sha256 = "",
        integrity = "sha256-NWkhF40Bd4LZcBrt0Je1HB6S4YbpQQEeowA5olCdlBc=",
        patches = [],
    ),
}
