"""Repository rule for the rfcc bzlmod hub repo.

The hub contains only toolchain() declarations. Target names are zero-padded
so lexicographic order matches priority order, since `:all` resolves
lexicographically (see Bazel toolchain resolution docs).
"""

load("//toolchains/private:source_spokes.bzl", "source_spoke_repo")

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

def source_spoke_aliases(tool, version):
    """Hub alias dicts re-exporting one source-mode ``(tool, version)`` spoke.

    Both dependency models publish the same version-neutral hub names so a
    consumer's BUILD file can reach a source archive without pinning the
    version: the bzlmod planner (``build_hub_aliases``) and the WORKSPACE
    shim (``built_toolchains._emit_workspace_hub``) call this with a version
    chosen their own way. Keeping the alias *shape* in one place means a new
    source tool can't be published under one model and silently missed by
    the other.

    Args:
        tool: source-mode tool name (e.g. "cmake").
        version: the exact patch version whose spoke to alias.

    Returns:
        A list of ``{"name", "actual"}`` dicts. The caller is responsible
        for sorting the merged result for deterministic BUILD emission.
    """
    repo = source_spoke_repo(tool, version)
    aliases = [
        {
            "actual": "@{repo}//:{tool}_built".format(repo = repo, tool = tool),
            "name": "{}_built".format(tool),
        },
        {
            "actual": "@{}//:all_srcs".format(repo),
            "name": "{}_src_all".format(tool),
        },
    ]
    if tool == "meson":
        aliases.append({
            "actual": "@{}//:meson.py".format(repo),
            "name": "meson_src_meson_py",
        })
        aliases.append({
            "actual": "@{}//:runtime".format(repo),
            "name": "meson_src_runtime",
        })
    return aliases

_BUILD_HEADER = """\
# AUTO-GENERATED by foreign_cc/extensions.bzl. Do not edit.

package(default_visibility = ["//visibility:public"])

"""

_TOOLCHAIN_TEMPLATE = """\
toolchain(
    name = {name},
    toolchain_type = {toolchain_type},
    toolchain = {toolchain},
{constraints}\
)

"""

_ALIAS_TEMPLATE = """\
alias(
    name = {name},
    actual = {actual},
)

"""

def _format_constraints(label_list, attr_name):
    if not label_list:
        return ""
    items = ",\n".join(["        " + repr(lbl) for lbl in label_list])
    return "    {} = [\n{},\n    ],\n".format(attr_name, items)

def _hub_repo_impl(rctx):
    parts = [_BUILD_HEADER]
    for entry in rctx.attr.toolchain_specs_json_list:
        # Each entry is a json.encode'd dict with keys:
        # name, toolchain_type, toolchain, exec_compatible_with, target_compatible_with
        spec = json.decode(entry)
        constraints = ""
        constraints += _format_constraints(
            spec.get("exec_compatible_with", []),
            "exec_compatible_with",
        )
        constraints += _format_constraints(
            spec.get("target_compatible_with", []),
            "target_compatible_with",
        )
        parts.append(_TOOLCHAIN_TEMPLATE.format(
            name = repr(spec["name"]),
            toolchain_type = repr(spec["toolchain_type"]),
            toolchain = repr(spec["toolchain"]),
            constraints = constraints,
        ))
    for entry in rctx.attr.alias_specs_json_list:
        spec = json.decode(entry)
        parts.append(_ALIAS_TEMPLATE.format(
            name = repr(spec["name"]),
            actual = repr(spec["actual"]),
        ))
    rctx.file("BUILD.bazel", "".join(parts))
    rctx.file("WORKSPACE", "")

hub_repo = repository_rule(
    implementation = _hub_repo_impl,
    attrs = {
        "alias_specs_json_list": attr.string_list(
            doc = "JSON-encoded alias specs (keys: name, actual), one per entry. " +
                  "Order is the order aliases appear in BUILD.bazel, after the " +
                  "toolchain entries.",
        ),
        "toolchain_specs_json_list": attr.string_list(
            doc = "JSON-encoded toolchain specs, one per entry. " +
                  "Order of this list is the order targets appear in BUILD.bazel.",
        ),
    },
)
