"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

GNUMAKE_SRCS = {
    "4.3": struct(
        urls = [
            "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.3.tar.gz",
            "http://ftpmirror.gnu.org/gnu/make/make-4.3.tar.gz",
        ],
        strip_prefix = "make-4.3",
        sha256 = "e05fdde47c5f7ca45cb697e973894ff4f5d79e13b750ed57d7b66d8defc78e19",
        integrity = "",
        patches = [Label("//toolchains/patches:make-4.3-reproducible-bootstrap.patch")],
    ),
    "4.3.x": struct(
        urls = [
            "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.3.tar.gz",
            "http://ftpmirror.gnu.org/gnu/make/make-4.3.tar.gz",
        ],
        strip_prefix = "make-4.3",
        sha256 = "e05fdde47c5f7ca45cb697e973894ff4f5d79e13b750ed57d7b66d8defc78e19",
        integrity = "",
        patches = [Label("//toolchains/patches:make-4.3-reproducible-bootstrap.patch")],
    ),
    "4.4": struct(
        urls = [
            "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.4.tar.gz",
            "http://ftpmirror.gnu.org/gnu/make/make-4.4.tar.gz",
        ],
        strip_prefix = "make-4.4",
        sha256 = "581f4d4e872da74b3941c874215898a7d35802f03732bdccee1d4a7979105d18",
        integrity = "",
        patches = [Label("//toolchains/patches:make-4.4-reproducible-bootstrap.patch")],
    ),
    "4.4.1": struct(
        urls = [
            "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz",
            "http://ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz",
        ],
        strip_prefix = "make-4.4.1",
        sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3",
        integrity = "",
        patches = [Label("//toolchains/patches:make-4.4.1-reproducible-bootstrap.patch")],
    ),
    "4.4.x": struct(
        urls = [
            "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz",
            "http://ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz",
        ],
        strip_prefix = "make-4.4.1",
        sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3",
        integrity = "",
        patches = [Label("//toolchains/patches:make-4.4.1-reproducible-bootstrap.patch")],
    ),
}
