"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

MESON_SRCS = {
    "0.63.0": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
        ],
        strip_prefix = "meson-0.63.0",
        sha256 = "3b51d451744c2bc71838524ec8d96cd4f8c4793d5b8d5d0d0a9c8a4f7c94cd6f",
        integrity = "",
        patches = [],
    ),
    "0.63.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
        ],
        strip_prefix = "meson-0.63.0",
        sha256 = "3b51d451744c2bc71838524ec8d96cd4f8c4793d5b8d5d0d0a9c8a4f7c94cd6f",
        integrity = "",
        patches = [],
    ),
    "1.1.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
        ],
        strip_prefix = "meson-1.1.1",
        sha256 = "d04b541f97ca439fb82fab7d0d480988be4bd4e62563a5ca35fadb5400727b1c",
        integrity = "",
        patches = [],
    ),
    "1.1.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
        ],
        strip_prefix = "meson-1.1.1",
        sha256 = "d04b541f97ca439fb82fab7d0d480988be4bd4e62563a5ca35fadb5400727b1c",
        integrity = "",
        patches = [],
    ),
    "1.10.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
        ],
        strip_prefix = "meson-1.10.1",
        sha256 = "c42296f12db316a4515b9375a5df330f2e751ccdd4f608430d41d7d6210e4317",
        integrity = "",
        patches = [],
    ),
    "1.10.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
        ],
        strip_prefix = "meson-1.10.1",
        sha256 = "c42296f12db316a4515b9375a5df330f2e751ccdd4f608430d41d7d6210e4317",
        integrity = "",
        patches = [],
    ),
    "1.5.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
        ],
        strip_prefix = "meson-1.5.1",
        sha256 = "567e533adf255de73a2de35049b99923caf872a455af9ce03e01077e0d384bed",
        integrity = "",
        patches = [],
    ),
    "1.5.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
        ],
        strip_prefix = "meson-1.5.1",
        sha256 = "567e533adf255de73a2de35049b99923caf872a455af9ce03e01077e0d384bed",
        integrity = "",
        patches = [],
    ),
}
