"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

MESON_SRCS = {
    "0.63.0": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
        ],
        strip_prefix = "meson-0.63.0",
        sha256 = "",
        integrity = "sha256-O1HUUXRMK8cYOFJOyNls1PjEeT1bjV0NCpyKT3yUzW8=",
        patches = [],
    ),
    "0.63.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz",
        ],
        strip_prefix = "meson-0.63.0",
        sha256 = "",
        integrity = "sha256-O1HUUXRMK8cYOFJOyNls1PjEeT1bjV0NCpyKT3yUzW8=",
        patches = [],
    ),
    "1.1.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
        ],
        strip_prefix = "meson-1.1.1",
        sha256 = "",
        integrity = "sha256-0EtUH5fKQ5+4L6t9DUgJiL5L1OYlY6XKNfrbVAByexw=",
        patches = [],
    ),
    "1.1.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz",
        ],
        strip_prefix = "meson-1.1.1",
        sha256 = "",
        integrity = "sha256-0EtUH5fKQ5+4L6t9DUgJiL5L1OYlY6XKNfrbVAByexw=",
        patches = [],
    ),
    "1.10.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
        ],
        strip_prefix = "meson-1.10.1",
        sha256 = "",
        integrity = "sha256-xCKW8S2zFqRRW5N1pd8zDy51HM3U9ghDDUHX1iEOQxc=",
        patches = [],
    ),
    "1.10.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.10.1/meson-1.10.1.tar.gz",
        ],
        strip_prefix = "meson-1.10.1",
        sha256 = "",
        integrity = "sha256-xCKW8S2zFqRRW5N1pd8zDy51HM3U9ghDDUHX1iEOQxc=",
        patches = [],
    ),
    "1.5.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
        ],
        strip_prefix = "meson-1.5.1",
        sha256 = "",
        integrity = "sha256-Vn5TOt8lXec6LeNQSbmZI8r4cqRVr5zgPgEHfg04S+0=",
        patches = [],
    ),
    "1.5.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
            "https://github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz",
        ],
        strip_prefix = "meson-1.5.1",
        sha256 = "",
        integrity = "sha256-Vn5TOt8lXec6LeNQSbmZI8r4cqRVr5zgPgEHfg04S+0=",
        patches = [],
    ),
}
