"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

NINJA_BIN_SRCS = {
    "1.10.2": {
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "763464859c7ef2ea3a0a10f4df40d2025d3bb9438fcb1228404640410c0ec22d",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "6fa359f491fac7e5185273c6421a000eea6a2f0febf0ac03ac900bd4d80ed2a5",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac_aarch64",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "6fa359f491fac7e5185273c6421a000eea6a2f0febf0ac03ac900bd4d80ed2a5",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "bbde850d247d2737c5764c927d1071cbb1f1957dcabda4a130fa8547c12c695f",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
            plat_target = "win",
        ),
    },
    "1.11.1": {
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "b901ba96e486dce377f9a070ed4ef3f79deb45f4ffe2938f8e7ddc69cfb3df77",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "482ecb23c59ae3d4f158029112de172dd96bb0e97549c4b1ca32d8fad11f873e",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac_aarch64",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "482ecb23c59ae3d4f158029112de172dd96bb0e97549c4b1ca32d8fad11f873e",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "524b344a1a9a55005eaf868d991e090ab8ce07fa109f1820d40e74642e289abc",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
            plat_target = "win",
        ),
    },
    "1.12.1": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux-aarch64.zip",
            ],
            strip_prefix = "",
            sha256 = "5c25c6570b0155e95fce5918cb95f1ad9870df5768653afe128db822301a05a1",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac_aarch64",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "f550fec705b6d6ff58f2db3c374c2277a37691678d6aba463adcbb129108467a",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
            plat_target = "win",
        ),
    },
    "1.13.2": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux-aarch64.zip",
            ],
            strip_prefix = "",
            sha256 = "fd2cacc8050a7f12a16a2e48f9e06fca5c14fc4c2bee2babb67b58be17a607fc",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux-aarch64",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
            plat_target = "linux",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b",
            integrity = "",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac_aarch64",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "c99048673aa765960a99cf10c6ddb9f1fad506099ff0a0e137ad8960a88f321b",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
            plat_target = "mac",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65",
            integrity = "",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
            plat_target = "win",
        ),
    },
}

NINJA_BIN_WILDCARDS = {
    "1.10.x": "1.10.2",
    "1.11.x": "1.11.1",
    "1.12.x": "1.12.1",
    "1.13.x": "1.13.2",
}

NINJA_BIN_REPO_FORMAT = "ninja_{version}_{plat_target}"

NINJA_SRC_SRCS = {
    "1.10.2": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
        ],
        strip_prefix = "ninja-1.10.2",
        sha256 = "ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed",
        integrity = "",
        patches = [],
    ),
    "1.10.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
        ],
        strip_prefix = "ninja-1.10.2",
        sha256 = "ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed",
        integrity = "",
        patches = [],
    ),
    "1.11.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
        ],
        strip_prefix = "ninja-1.11.1",
        sha256 = "31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea",
        integrity = "",
        patches = [],
    ),
    "1.11.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
        ],
        strip_prefix = "ninja-1.11.1",
        sha256 = "31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea",
        integrity = "",
        patches = [],
    ),
    "1.12.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
        ],
        strip_prefix = "ninja-1.12.1",
        sha256 = "821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a",
        integrity = "",
        patches = [],
    ),
    "1.12.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
        ],
        strip_prefix = "ninja-1.12.1",
        sha256 = "821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a",
        integrity = "",
        patches = [],
    ),
    "1.13.2": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
        ],
        strip_prefix = "ninja-1.13.2",
        sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17",
        integrity = "",
        patches = [],
    ),
    "1.13.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
        ],
        strip_prefix = "ninja-1.13.2",
        sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17",
        integrity = "",
        patches = [],
    ),
}
