"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

NINJA_BIN_SRCS = {
    "1.10.2": {
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-djRkhZx+8uo6ChD030DSAl07uUOPyxIoQEZAQQwOwi0=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-b6NZ9JH6x+UYUnPGQhoADupqLw/r8KwDrJAL1NgO0qU=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-b6NZ9JH6x+UYUnPGQhoADupqLw/r8KwDrJAL1NgO0qU=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-u96FDSR9JzfFdkySfRBxy7HxlX3KvaShMPqFR8EsaV8=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
    },
    "1.11.1": {
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-uQG6luSG3ON3+aBw7U7z953rRfT/4pOPjn3cac+z33c=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-SC7LI8Wa49TxWAKREt4XLdlrsOl1ScSxyjLY+tEfhz4=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-SC7LI8Wa49TxWAKREt4XLdlrsOl1ScSxyjLY+tEfhz4=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-Uks0ShqaVQBer4aNmR4JCrjOB/oQnxgg1A50ZC4omrw=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
    },
    "1.12.1": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux-aarch64.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-XCXGVwsBVelfzlkYy5XxrZhw31doZTr+Eo24IjAaBaE=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-b5iAVojRlnK9aZ+7+iws8PwFSsPfHw5qR2ZNlj1TAlU=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-iaKHREtbPpj4ipRa+lDOk3uP/R3MWcVVrZsbr4VSmMk=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-iaKHREtbPpj4ipRa+lDOk3uP/R3MWcVVrZsbr4VSmMk=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("windows", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-winarm64.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-eclqUODer+whLPqFqlfGt0AD9S2dFnPdzR6rHJWMWQA=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-9VD+xwW21v9Y8ts8N0wid6N2kWeNarpGOty7EpEIRno=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
    },
    "1.13.2": {
        ("linux", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux-aarch64.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-/SysyAUKfxKhai5I+eBvylwU/Ewr7iurtntYvhemB/w=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("linux", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-V0nLxOZoJzUUFQqA44epV/kzxu0/XxHgP7MJVeK76tY=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:linux",
            ],
            bin = "ninja",
        ),
        ("macos", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-yZBIZzqnZZYKmc8Qxt258frVBgmf8KDhN62JYKiPMhs=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("macos", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-mac.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-yZBIZzqnZZYKmc8Qxt258frVBgmf8KDhN62JYKiPMhs=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:macos",
            ],
            bin = "ninja",
        ),
        ("windows", "aarch64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-winarm64.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-5S8L3vnfsQAyKdvWUIpQjEBz/QFyRwAq3Gbl6AbLA5E=",
            constraints = [
                "@platforms//cpu:aarch64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
        ("windows", "x86_64"): struct(
            urls = [
                "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip",
            ],
            strip_prefix = "",
            sha256 = "",
            integrity = "sha256-B/yCYbQrIOcdFyCzkGjC4U/87mOWt2+3p5X7Rgt43GU=",
            constraints = [
                "@platforms//cpu:x86_64",
                "@platforms//os:windows",
            ],
            bin = "ninja.exe",
        ),
    },
}

NINJA_BIN_WILDCARDS = {
    "1.10.x": "1.10.2",
    "1.11.x": "1.11.1",
    "1.12.x": "1.12.1",
    "1.13.x": "1.13.2",
}

NINJA_SRC_SRCS = {
    "1.10.2": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
        ],
        strip_prefix = "ninja-1.10.2",
        sha256 = "ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed",
        integrity = "",
        patches = [],
    ),
    "1.10.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz",
        ],
        strip_prefix = "ninja-1.10.2",
        sha256 = "ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed",
        integrity = "",
        patches = [],
    ),
    "1.11.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
        ],
        strip_prefix = "ninja-1.11.1",
        sha256 = "31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea",
        integrity = "",
        patches = [],
    ),
    "1.11.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.11.1.tar.gz",
        ],
        strip_prefix = "ninja-1.11.1",
        sha256 = "31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea",
        integrity = "",
        patches = [],
    ),
    "1.12.1": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
        ],
        strip_prefix = "ninja-1.12.1",
        sha256 = "821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a",
        integrity = "",
        patches = [],
    ),
    "1.12.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.12.1.tar.gz",
        ],
        strip_prefix = "ninja-1.12.1",
        sha256 = "821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a",
        integrity = "",
        patches = [],
    ),
    "1.13.2": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
        ],
        strip_prefix = "ninja-1.13.2",
        sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17",
        integrity = "",
        patches = [],
    ),
    "1.13.x": struct(
        urls = [
            "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
            "https://github.com/ninja-build/ninja/archive/v1.13.2.tar.gz",
        ],
        strip_prefix = "ninja-1.13.2",
        sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17",
        integrity = "",
        patches = [],
    ),
}
