"""@generated by toolchains/prebuilt_toolchains.py - do not edit."""

visibility([
    "//foreign_cc",
    "//foreign_cc/private",
    "//toolchains",
])

PKGCONFIG_SRCS = {
    "0.29.2": struct(
        urls = [
            "https://mirror.bazel.build/pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz",
            "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz",
        ],
        strip_prefix = "pkg-config-0.29.2",
        sha256 = "6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591",
        integrity = "",
        patches = [Label("//toolchains/patches:pkgconfig-detectenv.patch"), Label("//toolchains/patches:pkgconfig-makefile-vc.patch"), Label("//toolchains/patches:pkgconfig-builtin-glib-int-conversion.patch")],
    ),
    "0.29.x": struct(
        urls = [
            "https://mirror.bazel.build/pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz",
            "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz",
        ],
        strip_prefix = "pkg-config-0.29.2",
        sha256 = "6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591",
        integrity = "",
        patches = [Label("//toolchains/patches:pkgconfig-detectenv.patch"), Label("//toolchains/patches:pkgconfig-makefile-vc.patch"), Label("//toolchains/patches:pkgconfig-builtin-glib-int-conversion.patch")],
    ),
}
