test_suite(
    name = "tests",
    tests = [
        "//examples/cmake:test_libgd",
        "//examples/cmake:test_libpng",
        "//examples/cmake:test_zlib",
        "//examples/cmake_cares:test_c_ares",
        "//examples/ninja:test_ninja_version",
    ],
)
