workspace(name = "rules_foreign_cc_tests")

local_repository(
    name = "rules_foreign_cc",
    path = "..",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies([
    "//:built_ninja_toolchain_osx",
    "//:built_ninja_toolchain_linux",
])

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("//deps:repositories.bzl", "repositories")

repositories()

android_sdk_repository(
    name = "androidsdk",
)

android_ndk_repository(
    name = "androidndk",
)

load("//deps:deps_jvm_external.bzl", "deps_jvm_external")

deps_jvm_external()
