"""Regen-tool stub constants used by configure_make.

Bazel materialises source files in the action sandbox with mtimes set to a
constant (the Unix epoch or thereabouts), which leaves the autogenerated
files in an autotools tree (`configure`, `aclocal.m4`, `Makefile.in`, ...)
with the same mtime as their `*.ac`/`*.am` inputs. `make`'s "rebuild if
target is not strictly newer than prerequisite" check then fires automake's
regeneration recipes at build time (e.g. `aclocal.m4: configure.ac` invokes
`aclocal-1.16` via automake's `missing` helper). The version-suffixed tools
are typically not installed on RBE workers, so the build fails. To prevent
this, configure_make injects `=true` defaults for the relevant tool variables
onto the configure command line; configure substitutes them into the
generated Makefile so the regeneration recipes become no-ops.
"""

# Default values injected onto the ./configure command line so that automake's
# `am_missing_run`-substituted Makefile rules become no-ops at make time.
REGEN_STUBS = {
    "ACLOCAL": "true",
    "AUTOCONF": "true",
    "AUTOHEADER": "true",
    "AUTOM4TE": "true",
    "AUTOMAKE": "true",
    "HELP2MAN": "true",
    "MAKEINFO": "true",
}
