workspace(name = "standard_cxx_flags_test")

local_repository(
    name = "rules_foreign_cc",
    path = "../..",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()
