workspace(name = "rules_foreign_cc_detect_root_test")

# We do not initialize rules_foreign_cc, because we only need to access
# detect_root.bzl file from them.
local_repository(
    name = "rules_foreign_cc",
    path = "../..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

new_local_repository(
    name = "rules_foreign_cc_detect_root_test_repo",
    build_file_content = """\
filegroup(
    name = "srcs", 
    srcs = glob(["**/**"]),
    visibility = ["//visibility:public"],
)
""",
    path = "dir1",
)
