load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

filegroup(
    name = "distribution",
    srcs = glob(["**"]),
    visibility = ["//:__subpackages__"],
)

bzl_library(
    name = "native_tools_toolchain",
    srcs = ["native_tools_toolchain.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "meson_tool_toolchain",
    srcs = ["meson_tool_toolchain.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":native_tools_toolchain",
        "@rules_python//python:py_executable_info_bzl",
        "@rules_python//python:py_info_bzl",
    ],
)

bzl_library(
    name = "tool_access",
    srcs = ["tool_access.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        ":native_tools_toolchain",
        "//foreign_cc/private/framework:exec_groups",
    ],
)
